// AUTO-GENERATED by scripts/gen-examples.py — do not edit by hand.
// Source: examples/playground/

export const EXAMPLES = [
    {
        id: "features",
        language: "javascript",
        label: "Type System",
        items: [
            {
                id: "basics",
                language: "javascript",
                label: "basics.js",
                blurb: "Inference for plain JavaScript",
                expect: "ok",
                code: `// Inty infers a type for every binding — no annotations needed.
// Hover anything to see the inferred type.

var n = 42;
var s = "hello";
var b = true;

function square(x) { return x * x; }
var nine = square(3);

function greet(name) { return "Hello, " + name; }
var hi = greet("world");
`,
            },
            {
                id: "generics",
                language: "javascript",
                label: "generics.js",
                blurb: "Parametric polymorphism",
                expect: "ok",
                code: `// A function that doesn't constrain its inputs becomes polymorphic.
// Inty infers \`id<a>(a) => a\`.

function id(x) { return x; }

var n   = id(42);
var s   = id("hello");
var arr = id([1, 2, 3]);

// One function, three call sites — each instantiated at a fresh type.
`,
            },
            {
                id: "structural",
                language: "javascript",
                label: "structural.js",
                blurb: "Row polymorphism \u2014 typed by shape",
                expect: "ok",
                code: `// Objects are typed structurally — by what fields they carry.
// \`getName\` works on *anything* with a \`name\` field.

function getName(obj) { return obj.name; }

var alice = getName({ name: "Alice", age: 30 });
var rover = getName({ name: "Rover", breed: "Labrador" });
var ship  = getName({ name: "USS Enterprise", warpFactor: 9 });

// Inty infers \`getName<a, b>({name: a | b}) => a\` —
// only \`name\` is required; the row variable \`b\` carries the rest.
`,
            },
            {
                id: "overloading",
                language: "javascript",
                label: "overloading.js",
                blurb: "Operator type classes",
                expect: "ok",
                code: `// \`+\` works on any addable type — Number or String.
// Inty infers \`add<a> where Plus a => (a, a) => a\`.

function add(x, y) { return x + y; }

var sum    = add(1, 2);
var concat = add("foo", "bar");

// The call site picks the instance. Mixing them is a type error:
// var bad = add(1, "two");   // error!
`,
            },
            {
                id: "unions",
                language: "javascript",
                label: "unions.js",
                blurb: "Control-flow joins",
                expect: "ok",
                code: `// Branches that disagree on type are *joined* into a closed union.

function tag(c) { return c ? 42 : "err"; }
var t = tag(true);                  // Number | String

// Arrays:
var mixed = [1, "two", 3];          // (Number | String)[]
var first = ["a", 2][0];            // Number | String

// Object branches with disjoint shapes:
function pick(b) {
    return b ? { x: 1, y: 2 } : { x: 3, z: 4 };
}
var pt = pick(true);
var x  = pt.x;                      // both branches expose \`x: Number\`
`,
            },
            {
                id: "method-chaining",
                language: "javascript",
                label: "method-chaining.js",
                blurb: "Equi-recursive builder types",
                expect: "ok",
                code: `// Builder pattern — \`return this\` produces equi-recursive types.
// The chain types itself, no annotations.

var request = {
    url: "",
    method: "GET",
    setUrl:    function(u) { this.url = u;    return this; },
    setMethod: function(m) { this.method = m; return this; },
    send:      function()  { return this.method + " " + this.url; }
};

var response = request
    .setUrl("/api/users")
    .setMethod("POST")
    .send();
`,
            },
            {
                id: "tagged-unions",
                language: "javascript",
                label: "tagged-unions.js",
                blurb: "Discriminated unions + narrowing",
                expect: "ok",
                code: `// A tagged union — a single value that's exactly one of N known shapes.
// \`shape.kind === "..."\` refines the type inside each branch.

/** function area(s: {kind: "circle", r: Number}
                 | {kind: "square", s: Number}) => Number */
function area(shape) {
    if (shape.kind === "circle") {
        return shape.r;             // shape narrowed to circle
    } else {
        return shape.s;             // shape narrowed to square
    }
}

var a = area({ kind: "circle", r: 10 });
var b = area({ kind: "square", s:  5 });
`,
            },
            {
                id: "nullable",
                language: "javascript",
                label: "nullable.js",
                blurb: "Optional values, ??, narrowing",
                expect: "ok",
                code: `// Postfix \`T?\` desugars to \`T | Undefined\`.
// Composes with the existing union machinery — \`??\`, narrowing.

var arr = [1, 2, 3];
var v   = arr.find(function(n) { return n > 0; });   // Number | Undefined

// Defaulting:
var pick = v ?? 0;                                    // Number

// Narrowing:
var safe = (typeof v === "undefined") ? 0 : v;       // Number
`,
            },
            {
                id: "optional-fields",
                language: "javascript",
                label: "optional-fields.js",
                blurb: "Row-field presence polymorphism",
                expect: "ok",
                code: `// Optional row fields with presence polymorphism (Rémy 1994).
//
// \`name?: T\` in a row annotation marks the field *presence-polymorphic*:
// the caller may supply it or omit it, and the field's type is plain
// \`T\` — not \`T | Undefined\`. Optionality lives in the row, not in the
// value's type.

/** function request(opts: {url: String, method?: String, body?: String}) => String */
function request(opts) {
    // The body only reads \`opts.url\`. \`method\` and \`body\` stay
    // presence-polymorphic, so each call site decides independently
    // whether to supply them.
    return opts.url;
}

var a = request({url: "/api"});                                  // ok — method, body absent
var b = request({url: "/api", method: "POST"});                  // ok — method present, body absent
var c = request({url: "/api", method: "POST", body: "hello"});   // ok — both present

// Closed-row strictness still applies. Unknown fields don't fit:
//
// var d = request({url: "/api", verb: "POST"});
//   error: extra field \`verb\` doesn't appear in the row.

// If the body had read \`opts.method\`, the presence variable for
// \`method\` would be pinned to \`Pre\`, and the no-method call (\`a\`
// above) would fail to unify. Reading a field demands presence.
`,
            },
            {
                id: "classes",
                language: "javascript",
                label: "classes.js",
                blurb: "Class bodies + private fields",
                expect: "ok",
                code: `// Class declarations desugar to factory functions returning a row of
// methods + fields. \`#name\` private fields lower to a sentinel key —
// unreachable from outside.

class Counter {
    #count = 0;
    inc() {
        this.#count = this.#count + 1;
        return this.#count;
    }
    get current() { return this.#count; }
}

var c = new Counter();
var n = c.inc();           // Number
var v = c.current;         // Number

// Try this — uncomment to see the parse error:
// var leak = c.#count;   // error!
`,
            },
            {
                id: "callable-rows",
                language: "javascript",
                label: "callable-rows.js",
                blurb: "Functions are rows with statics",
                expect: "ok",
                code: `// Functions are *rows* — a call signature plus optional named fields.
// So \`String(42)\` and \`String.fromCharCode(65)\` are the same value
// used two different ways.

var c = String.fromCharCode(65);   // "A"
var s = String(42);                // "42"

var arr = [1, 2, 3];
var stringified = arr.map(String); // String[]

// Passing \`String\` where \`.map\` expects a function is pure row
// polymorphism — no special "constructor type" rule.
`,
            },
            {
                id: "higher-order",
                language: "javascript",
                label: "higher-order.js",
                blurb: "First-class functions",
                expect: "ok",
                code: `// Functions are first-class. Inty handles higher-order use directly.

function compose(f, g) {
    return function(x) { return f(g(x)); };
}

function double(x) { return x * 2; }
function inc(x)    { return x + 1; }

var f = compose(double, inc);
var n = f(3);                       // (3 + 1) * 2 = 8

// \`compose\` is fully polymorphic — works for any matching pair.
var g = compose(function(s) { return s + "!"; },
                function(s) { return s + s; });
var loud = g("yo");                 // "yoyo!"
`,
            },
            {
                id: "jsdoc-at-type",
                language: "javascript",
                label: "jsdoc-at-type.js",
                blurb: "JSDoc @type on object fields",
                expect: "ok",
                code: `// JSDoc \`@type\` annotations on object-literal fields.
//
// A widespread JS pattern (popularised by htmx, jQuery, lodash):
// declare a public-API object with \`null\`-initialised fields, then
// fill them in with forward-declared helpers. \`@type {typeof helper}\`
// tells the type checker what type the field will end up holding —
// the \`null\` is just a placeholder, not the real value.

const api = {
    /** @type {typeof greet} */
    greet: null,
    /** @type {typeof add} */
    add: null,

    // The bare form \`@type T\` (no braces) is also accepted —
    // this is the older JSDoc convention.
    /**
     * @type Boolean
     * @default true
     */
    enabled: true,
};

// Helpers declared *after* the object literal — function declarations
// hoist (via SCC analysis), so \`typeof greet\` works above.
function greet(name) { return "Hello, " + name; }
function add(x, y)   { return x + y; }

// Late assignment fills in the placeholders.
api.greet = greet;
api.add   = add;

// \`api.greet\` is typed as \`(String) => String\`, not \`Null\`, because
// of the \`@type\` annotation.
var msg = api.greet("world");
var n   = api.add(1, 2);

// The \`enabled\` field is \`Boolean\` (not the literal \`true\`).
var on  = api.enabled && true;

// A non-placeholder value still type-checks against the annotation:
// uncomment the next line to see the error.
// var bad = { /** @type {Number} */ count: "oops" }; // error!
`,
            },
        ],
    },
    {
        id: "ts-misses",
        language: "javascript",
        label: "TS wouldn't catch this",
        items: [
            {
                id: "string-plus-number",
                language: "javascript",
                label: "string-plus-number.js",
                blurb: "`+` silently coerces in TS",
                expect: "error",
                code: `// TypeScript happily allows String + Number — JavaScript coerces,
// and so does the TS \`+\` rule. The intent is almost always wrong.
//
// Inty's \`Plus\` type class requires both operands to be the *same*
// instance: two Numbers, or two Strings. No silent coercion.

var count = 3;
var msg   = "Got " + count + " items";

// Inty: error — operands disagree.
// At runtime: "Got 3 items" (works by accident).
//
// The fix says what you mean:
//   var msg = "Got " + String(count) + " items";
`,
            },
            {
                id: "or-fallback",
                language: "javascript",
                label: "or-fallback.js",
                blurb: "Truthy fallback hides type changes",
                expect: "ok",
                code: `// In JavaScript, \`||\` returns one of its operands — not a boolean.
// So \`0 || "Guest"\` evaluates to "Guest" and the variable's type
// silently widens to \`Number | String\`.
//
// TypeScript: tolerates the union without complaint.
// Inty: infers \`label(String) => String\` — calling with a Number
// fails at the call site, not silently inside the body.

function label(n) {
    var name = n || "Guest";        // n: Number, fallback: String — mismatch
    return name;
}

// Pass a Number to expose the bug:
// var r = label(3);   // error!

// Fix: make the default match the type, or convert explicitly.
//   var name = n === 0 ? "Guest" : String(n);
`,
            },
            {
                id: "mixed-array",
                language: "javascript",
                label: "mixed-array.js",
                blurb: "Mixed arrays look uniform in TS",
                expect: "error",
                code: `// Without annotations, TypeScript widens this to \`(string | number)[]\`
// and lets you use any element as if it were either type.
// Inty types it as a closed union and forces a narrow before use.

var items = [1, "two", 3, "four"];

// In TS: items[0].toFixed(2) compiles (because of \`number\` in the union).
// At runtime: TypeError when the element is actually a string.
//
// Inty: \`.toFixed\` isn't on the union — you must narrow first.
function describe(x) {
    if (typeof x === "number") { return x.toFixed(2); }
    else                       { return x.toUpperCase(); }
}
var first = describe(items[0]);
`,
            },
            {
                id: "missing-prop",
                language: "javascript",
                label: "missing-prop.js",
                blurb: "Reading a property that isn't there",
                expect: "error",
                code: `// Object literals produce *closed* rows in inty — what you wrote is
// all that's there. Reading a missing field is a structural error.
//
// In TypeScript without explicit types, this often types as \`any\`
// (via implicit-any or noImplicitAny=false) and slips through.

function fullName(user) {
    return user.firstName + " " + user.lastName;
}

var name = fullName({ name: "Alice", id: 42 });
//                        ^^^^^^^^^^^^^^^^^^
// Inty: \`firstName\` not found in \`{name: String, id: Number}\`.
// TS (.js, no types): silently \`any\` — caller sees no error.
`,
            },
            {
                id: "this-leak",
                language: "javascript",
                label: "this-leak.js",
                blurb: "Methods called without their receiver",
                expect: "ok",
                code: `// Pulling a method off an object loses \`this\`. TypeScript with default
// settings types it as a plain function and lets you call it standalone.
// At runtime it explodes — \`this\` is undefined.
//
// Inty: \`this\` is part of the method's row type. The free function and
// the bound method aren't interchangeable.

var counter = {
    n: 0,
    inc: function() { this.n = this.n + 1; return this.n; }
};

var inc = counter.inc;
// var oops = inc();   // error!
// ↑ uncomment: at runtime, TypeError.
//   Inty rejects at type-check time.

var ok = counter.inc();
`,
            },
            {
                id: "truthy-narrow",
                language: "javascript",
                label: "truthy-narrow.js",
                blurb: "0 and \"\" are falsy \u2014 silently",
                expect: "ok",
                code: `// JavaScript treats 0, "", NaN, null, undefined all as falsy.
// TypeScript's narrowing on \`if (x)\` doesn't distinguish between
// "missing" and "empty/zero" — easy bug.

function priceLabel(price) {
    if (price) { return "$" + price; }
    else       { return "free"; }
}

// Inty infers \`priceLabel(String) => String\` — the \`+\` inside fixes
// \`price\` to a String. Calling with the literal \`0\` then errors at
// the call site:
// var lbl = priceLabel(0);   // error!
//
// In TS, calling this with the literal \`0\` is fine — and silently
// returns "free" for a perfectly valid price of zero.
//
// The deeper fix — explicit \`price === undefined\` narrowing — is
// enforceable because inty types optional values as a real union.
`,
            },
        ],
    },
    {
        id: "py-features",
        language: "python",
        label: "Type System",
        items: [
            {
                id: "py-basics",
                language: "python",
                label: "basics.py",
                blurb: "Inference for plain Python",
                expect: "ok",
                code: `# Functions, assignment, arithmetic, string concatenation and a
# for-each loop over a list. Types are inferred throughout.

def add(a, b):
    return a + b

def double(n):
    return n * 2

total = 0
for i in [1, 2, 3, 4, 5]:
    total = total + add(i, double(i))

label = "total = " + "done"
`,
            },
            {
                id: "py-annotations",
                language: "python",
                label: "annotations.py",
                blurb: "Type hints enforced as constraints",
                expect: "ok",
                code: `# Type annotations are enforced as constraints, not discarded. A
# program whose values match its annotations type-checks. Annotations
# inty doesn't model (e.g. \`SomeProtocol\`) impose no constraint, so they
# never cause a false positive.

def add_one(x: int) -> int:
    return x + 1

def greet(name: str) -> str:
    return "hi " + name

def total(xs: list[int]) -> int:
    s = 0
    for v in xs:
        s = s + v
    return s

count: int = 5
label: str = "app"
r = add_one(10)
m = total([1, 2, 3])

class Counter:
    def __init__(self):
        self.v = 0
    def scaled(self, k: int) -> int:
        return self.v * k

c = Counter()
out = c.scaled(3)

# Unmodelled annotation: lowers to a fresh variable, constrains nothing.
def use(p: SomeProtocol):
    return 1

ignored = use("anything")
also = use(42)
`,
            },
            {
                id: "py-control",
                language: "python",
                label: "control.py",
                blurb: "if/elif/else and while loops",
                expect: "ok",
                code: `# Control flow: if/elif/else, a while loop, and a conditional
# expression. All branches of \`classify\` return strings.

def classify(n):
    if n < 0:
        return "negative"
    elif n == 0:
        return "zero"
    else:
        return "positive"

label = classify(5)

i = 0
while i < 5:
    i = i + 1

sign = "pos" if i > 0 else "nonpos"
`,
            },
            {
                id: "py-records",
                language: "python",
                label: "records.py",
                blurb: "Dicts with literal keys are records",
                expect: "ok",
                code: `# Dicts with string-literal keys are records: \`d["field"]\` lowers to a
# field read, so structural typing applies just like in JavaScript.

def make_point(x, y):
    return {"x": x, "y": y}

def length_squared(p):
    return p["x"] * p["x"] + p["y"] * p["y"]

origin = make_point(0, 0)
p = make_point(3, 4)
d = length_squared(p)

config = {"name": "app", "version": 1, "enabled": True}
title = config["name"]
`,
            },
            {
                id: "py-generics",
                language: "python",
                label: "generics.py",
                blurb: "Parametric polymorphism",
                expect: "ok",
                code: `# A function that doesn't constrain its inputs becomes polymorphic.
# Inty infers \`id<a>(a) => a\` — one definition, every call site
# instantiates at its own type.

def id(x):
    return x

def pair(a, b):
    return [a, b]

n = id(42)               # Number
s = id("hello")          # String

nums  = pair(1, 2)       # list[Number]
words = pair("hi", "yo") # list[String]
`,
            },
            {
                id: "py-classes",
                language: "python",
                label: "classes.py",
                blurb: "Methods, fields, nominal brands",
                expect: "ok",
                code: `# A class lowers to a factory function returning a row of methods +
# fields. \`__init__\` pins the field types; methods read them through
# \`self\`. Different classes are distinct nominal brands even when
# their shape is identical.

class Counter:
    def __init__(self, start):
        self.value = start
    def inc(self):
        self.value = self.value + 1
        return self.value
    def get(self):
        return self.value

c = Counter(0)
a = c.inc()
b = c.inc()
v = c.get()

# Try this — fields keep the type fixed by __init__:
# c.value = "oops"   # error!
`,
            },
            {
                id: "py-tagged-unions",
                language: "python",
                label: "tagged-unions.py",
                blurb: "isinstance narrows a brand union",
                expect: "ok",
                code: `# A union of two brands. The brand-specific methods are only safe
# to call inside the matching \`isinstance\` branch — outside it,
# inty rejects the access.

class Dog:
    def __init__(self):
        self.legs = 4
    def bark(self):
        return "woof"

class Cat:
    def __init__(self):
        self.legs = 4
    def meow(self):
        return "miaow"

animal = Dog() if True else Cat()

# Each branch narrows \`animal\` to a single brand, so the brand-
# specific method type-checks here.
if isinstance(animal, Dog):
    dog_sound = animal.bark()
else:
    cat_sound = animal.meow()

# Try this — uncomment to see narrowing in action:
# leak = animal.bark()   # error!
`,
            },
            {
                id: "py-higher-order",
                language: "python",
                label: "higher-order.py",
                blurb: "First-class functions, compose",
                expect: "ok",
                code: `# Functions are first-class. \`compose\` is fully polymorphic — inty
# infers \`compose<a, b, c>((b) => c, (a) => b) => ((a) => c)\`.

def compose(f, g):
    def composed(x):
        return f(g(x))
    return composed

def double(n):
    return n * 2

def inc(n):
    return n + 1

f = compose(double, inc)
m = f(3)              # (3 + 1) * 2 == 8

# Same compose, different types — strings flow through fine.
def loud(s):
    return s + "!"
def repeat(s):
    return s + s

g = compose(loud, repeat)
hi = g("yo")          # "yoyo!"
`,
            },
            {
                id: "py-type-aliases",
                language: "python",
                label: "type-aliases.py",
                blurb: "Literal aliases pin a string set",
                expect: "ok",
                code: `# \`Literal[...]\` constrains a value to a fixed set of strings. The
# alias makes the set reusable; passing a value outside the set is a
# type error — caught here, not as a \`ValueError\` at runtime.

BumpType = Literal["patch", "minor", "major"]

def next_version(kind: BumpType) -> BumpType:
    return kind

a = next_version("patch")
b = next_version("minor")
c = next_version("major")

# Try this — uncomment to see the alias enforce its set:
# d = next_version("majr")   # error!
`,
            },
            {
                id: "py-tuples",
                language: "python",
                label: "tuples.py",
                blurb: "Tuples + positional destructuring",
                expect: "ok",
                code: `# Tuples are typed positionally. Returning one and destructuring it
# at the call site preserves each element's type — \`q\` is a Number,
# \`r\` is a Number, and the program type-checks across the seam.

def divmod_pair(a, b):
    return (a // b, a % b)

q, r = divmod_pair(17, 5)
total = q + r

# A heterogeneous tuple keeps each slot's type distinct.
def labelled(n, name):
    return (n, name + "!")

count, tag = labelled(3, "items")
ok = count + 1
caption = tag + " ok"
`,
            },
            {
                id: "py-list-methods",
                language: "python",
                label: "list-methods.py",
                blurb: "append/extend/pop/sort/index",
                expect: "ok",
                code: `# Inty exposes the Python \`list\` method surface — not the JavaScript
# one. The methods you'd reach for at the REPL all type-check.

xs = [3, 1, 4, 1, 5]
xs.append(9)
xs.extend([2, 6])
xs.insert(0, 0)

n = xs.count(1)       # how many 1s
i = xs.index(4)       # first position of 4

xs.sort()
xs.reverse()
last = xs.pop()       # Number

ys = ["banana", "apple", "cherry"]
ys.sort()
top = ys[0]           # String
`,
            },
            {
                id: "py-str-methods",
                language: "python",
                label: "str-methods.py",
                blurb: "upper/split/join/replace/startswith",
                expect: "ok",
                code: `# Python \`str\` methods are typed individually. Each call's result
# flows through the rest of the program with its real type.

s = "Hello, World"

upper = s.upper()                  # String
parts = s.split(", ")              # list[String]
joined = " / ".join(parts)         # String
clean = "  hi  ".strip()           # String
swapped = s.replace("World", "Inty")
yes = s.startswith("Hello")        # Bool
n = len(s)                         # Number
`,
            },
            {
                id: "py-f-strings",
                language: "python",
                label: "f-strings.py",
                blurb: "f-strings type-check embedded code",
                expect: "ok",
                code: `# F-strings are typed end-to-end. Each interpolation is checked,
# so misspelt names or type errors inside \`{ … }\` surface here, not
# at runtime.

def greeting(name, count):
    return f"hi {name}, this is message #{count + 1}"

msg = greeting("ada", 0)

# Method calls and arithmetic both work inside the braces.
items = ["apple", "fig"]
header = f"{len(items)} items, starting with {items[0].upper()}"
`,
            },
            {
                id: "py-builtins",
                language: "python",
                label: "builtins.py",
                blurb: "range, sorted, sum, abs, str, len",
                expect: "ok",
                code: `# Inty's Python prelude types core builtins precisely. \`abs\` is
# \`(Number) -> Number\`, \`range\` produces something you can iterate
# over as Number, \`sorted\` is generic over the element type.

x = abs(-7)                 # Number
total = sum([1, 2, 3])      # Number

words = sorted(["pear", "apple", "fig"])
first = words[0]            # String

count = 0
for i in range(10):
    count = count + i

label = str(count)          # Number -> String
yes = all([True, True])     # Bool
`,
            },
        ],
    },
    {
        id: "py-misses",
        language: "python",
        label: "Mistakes mypy lets slip",
        items: [
            {
                id: "py-mixed-plus",
                language: "python",
                label: "mixed-plus.py",
                blurb: "`+` requires matching operand types",
                expect: "error",
                code: `# inty rejects mixing operand types: \`+\` requires both operands to
# share one type. This is a type error, by design.

x = 1 + "oops"
`,
            },
            {
                id: "py-unknown-field",
                language: "python",
                label: "unknown-field.py",
                blurb: "Reading a key the dict doesn't have",
                expect: "error",
                code: `# The dict literal gives \`p\` a closed shape \`{"x", "y"}\`. Reading a key
# it doesn't have is a type error.

p = {"x": 1, "y": 2}
bad = p["z"]
`,
            },
            {
                id: "py-bad-annotation",
                language: "python",
                label: "bad-annotation.py",
                blurb: "Value contradicts its annotation",
                expect: "error",
                code: `# A value that contradicts its annotation is a type error. Here the
# variable is annotated \`int\` but initialised with a String, so inty
# rejects the program.

n: int = "not a number"
`,
            },
            {
                id: "py-field-mismatch",
                language: "python",
                label: "field-mismatch.py",
                blurb: "self.field type fixed by __init__",
                expect: "error",
                code: `# \`__init__\` ties each field to its initial type. Inside any method
# that reads \`self.name\`, the field is a \`String\` — adding a Number
# to it is a type error, by design.

class Greeter:
    def __init__(self, name):
        self.name = name
    def shout(self, times):
        return self.name + times   # String + Number — rejected

g = Greeter("ada")
out = g.shout(3)
`,
            },
            {
                id: "py-keyword-typo",
                language: "python",
                label: "keyword-typo.py",
                blurb: "Misspelt keyword argument name",
                expect: "error",
                code: `# Keyword arguments resolve by name against the callee's parameter
# list. A misspelt keyword has no matching parameter — caught here,
# not as a TypeError at runtime.

def make_user(name, age):
    return {"name": name, "age": age}

# \`nme\` is a typo for \`name\`. Python runs it as a TypeError; inty
# rejects it statically.
u = make_user(nme="ada", age=36)
`,
            },
            {
                id: "py-missing-arg",
                language: "python",
                label: "missing-arg.py",
                blurb: "A required argument left unfilled",
                expect: "error",
                code: `# A required parameter must be supplied — either positionally or by
# name. Forgetting one is a static error.

def transfer(src, dst, amount):
    return {"from": src, "to": dst, "amount": amount}

# Forgot \`dst\`. Python: TypeError at the call site. Inty: caught.
r = transfer(src="checking", amount=50)
`,
            },
            {
                id: "py-distinct-brands",
                language: "python",
                label: "distinct-brands.py",
                blurb: "Twin classes are still distinct types",
                expect: "error",
                code: `# Two classes with the *same shape* are still different types —
# nominal typing. Trying to use one where the other is expected is
# rejected even when the fields and methods match exactly.

class Meters:
    def __init__(self, n):
        self.value = n

class Seconds:
    def __init__(self, n):
        self.value = n

distance = Meters(100)
distance = Seconds(60)   # different brand — rejected
`,
            },
            {
                id: "py-union-no-narrow",
                language: "python",
                label: "union-no-narrow.py",
                blurb: "Brand-specific method without isinstance",
                expect: "error",
                code: `# A union value has only the methods common to *all* its branches.
# A brand-specific method requires an \`isinstance\` check first —
# without one, inty rejects the access.

class Dog:
    def __init__(self):
        self.legs = 4
    def bark(self):
        return "woof"

class Cat:
    def __init__(self):
        self.legs = 4
    def meow(self):
        return "miaow"

animal = Dog() if True else Cat()

# No narrowing yet — \`bark\` exists on Dog only.
sound = animal.bark()
`,
            },
            {
                id: "py-literal-out-of-set",
                language: "python",
                label: "literal-out-of-set.py",
                blurb: "Literal alias rejects unknown strings",
                expect: "error",
                code: `# \`Literal["...", "..."]\` declares the exact strings allowed.
# Passing one outside the set is a static error — no typo can slip
# through to a \`raise ValueError\` at runtime.

LogLevel = Literal["debug", "info", "warn", "error"]

def log(level: LogLevel, msg: str) -> None:
    pass

log("info", "starting up")
log("warm", "uh oh")   # typo for "warn"
`,
            },
            {
                id: "py-js-method-on-py",
                language: "python",
                label: "js-method-on-py.py",
                blurb: "JS methods don't exist on Python types",
                expect: "error",
                code: `# Methods are language-specific. JavaScript array methods don't
# exist on a Python \`list\`, and JavaScript string methods don't
# exist on a Python \`str\`. Inty enforces the Python surface.

xs = [1, 2, 3]
xs.push(4)              # JS Array.push — not a Python list method

s = "hello"
c = s.charAt(0)         # JS String.charAt — not a Python str method
`,
            },
            {
                id: "py-return-type",
                language: "python",
                label: "return-type-mismatch.py",
                blurb: "`-> int` annotation is enforced",
                expect: "error",
                code: `# A \`-> int\` annotation is enforced. Returning a String from a
# function the type system promised would yield an \`int\` is rejected.

def total_price(quantity: int, price: int) -> int:
    # Easy to swap by accident when refactoring.
    return f"total: {quantity * price}"

t = total_price(3, 10)
`,
            },
            {
                id: "py-none-return",
                language: "python",
                label: "none-return.py",
                blurb: "Missing `return` makes the result None",
                expect: "error",
                code: `# A function that doesn't \`return\` anything returns \`None\`, not the
# value of its last expression statement. Using that None as if it
# were a Number is a bug Python only spots when the addition runs.

def log(msg):
    f"[log] {msg}"     # no \`return\` — the value is thrown away

x = log("starting") + 1
`,
            },
        ],
    },
];

export function findExample(id) {
    for (const section of EXAMPLES) {
        for (const item of section.items) {
            if (item.id === id) return { section, item };
        }
    }
    return null;
}

export const DEFAULT_EXAMPLE_IDS = {"javascript": "basics", "python": "py-basics"};
export const DEFAULT_EXAMPLE_ID = "basics";
