// AUTO-GENERATED by scripts/gen-examples.py — do not edit by hand.
// Source: examples/playground/

export const EXAMPLES = [
    {
        id: "features",
        label: "Type System",
        items: [
            {
                id: "basics",
                label: "basics.js",
                blurb: "Inference for plain JavaScript",
                expect: "ok",
                code: `// Inty infers a type for every binding — no annotations needed.
// Hover anything to see the inferred type.

var n = 42;
var s = "hello";
var b = true;

function square(x) { return x * x; }
var nine = square(3);

function greet(name) { return "Hello, " + name; }
var hi = greet("world");
`,
            },
            {
                id: "generics",
                label: "generics.js",
                blurb: "Parametric polymorphism",
                expect: "ok",
                code: `// A function that doesn't constrain its inputs becomes polymorphic.
// Inty infers \`id<a>(a) => a\`.

function id(x) { return x; }

var n   = id(42);
var s   = id("hello");
var arr = id([1, 2, 3]);

// One function, three call sites — each instantiated at a fresh type.
`,
            },
            {
                id: "structural",
                label: "structural.js",
                blurb: "Row polymorphism \u2014 typed by shape",
                expect: "ok",
                code: `// Objects are typed structurally — by what fields they carry.
// \`getName\` works on *anything* with a \`name\` field.

function getName(obj) { return obj.name; }

var alice = getName({ name: "Alice", age: 30 });
var rover = getName({ name: "Rover", breed: "Labrador" });
var ship  = getName({ name: "USS Enterprise", warpFactor: 9 });

// Inty infers \`getName<a, b>({name: a | b}) => a\` —
// only \`name\` is required; the row variable \`b\` carries the rest.
`,
            },
            {
                id: "overloading",
                label: "overloading.js",
                blurb: "Operator type classes",
                expect: "ok",
                code: `// \`+\` works on any addable type — Number or String.
// Inty infers \`add<a> where Plus a => (a, a) => a\`.

function add(x, y) { return x + y; }

var sum    = add(1, 2);
var concat = add("foo", "bar");

// The call site picks the instance. Mixing them is a type error:
// var bad = add(1, "two");   // error!
`,
            },
            {
                id: "unions",
                label: "unions.js",
                blurb: "Control-flow joins",
                expect: "ok",
                code: `// Branches that disagree on type are *joined* into a closed union.

function tag(c) { return c ? 42 : "err"; }
var t = tag(true);                  // Number | String

// Arrays:
var mixed = [1, "two", 3];          // (Number | String)[]
var first = ["a", 2][0];            // Number | String

// Object branches with disjoint shapes:
function pick(b) {
    return b ? { x: 1, y: 2 } : { x: 3, z: 4 };
}
var pt = pick(true);
var x  = pt.x;                      // both branches expose \`x: Number\`
`,
            },
            {
                id: "method-chaining",
                label: "method-chaining.js",
                blurb: "Equi-recursive builder types",
                expect: "ok",
                code: `// Builder pattern — \`return this\` produces equi-recursive types.
// The chain types itself, no annotations.

var request = {
    url: "",
    method: "GET",
    setUrl:    function(u) { this.url = u;    return this; },
    setMethod: function(m) { this.method = m; return this; },
    send:      function()  { return this.method + " " + this.url; }
};

var response = request
    .setUrl("/api/users")
    .setMethod("POST")
    .send();
`,
            },
            {
                id: "tagged-unions",
                label: "tagged-unions.js",
                blurb: "Discriminated unions + narrowing",
                expect: "ok",
                code: `// A tagged union — a single value that's exactly one of N known shapes.
// \`shape.kind === "..."\` refines the type inside each branch.

/** function area(s: {kind: "circle", r: Number}
                 | {kind: "square", s: Number}) => Number */
function area(shape) {
    if (shape.kind === "circle") {
        return shape.r;             // shape narrowed to circle
    } else {
        return shape.s;             // shape narrowed to square
    }
}

var a = area({ kind: "circle", r: 10 });
var b = area({ kind: "square", s:  5 });
`,
            },
            {
                id: "nullable",
                label: "nullable.js",
                blurb: "Optional values, ??, narrowing",
                expect: "ok",
                code: `// Postfix \`T?\` desugars to \`T | Undefined\`.
// Composes with the existing union machinery — \`??\`, narrowing.

var arr = [1, 2, 3];
var v   = arr.find(function(n) { return n > 0; });   // Number | Undefined

// Defaulting:
var pick = v ?? 0;                                    // Number

// Narrowing:
var safe = (typeof v === "undefined") ? 0 : v;       // Number
`,
            },
            {
                id: "optional-fields",
                label: "optional-fields.js",
                blurb: "Row-field presence polymorphism",
                expect: "ok",
                code: `// Optional row fields with presence polymorphism (Rémy 1994).
//
// \`name?: T\` in a row annotation marks the field *presence-polymorphic*:
// the caller may supply it or omit it, and the field's type is plain
// \`T\` — not \`T | Undefined\`. Optionality lives in the row, not in the
// value's type.

/** function request(opts: {url: String, method?: String, body?: String}) => String */
function request(opts) {
    // The body only reads \`opts.url\`. \`method\` and \`body\` stay
    // presence-polymorphic, so each call site decides independently
    // whether to supply them.
    return opts.url;
}

var a = request({url: "/api"});                                  // ok — method, body absent
var b = request({url: "/api", method: "POST"});                  // ok — method present, body absent
var c = request({url: "/api", method: "POST", body: "hello"});   // ok — both present

// Closed-row strictness still applies. Unknown fields don't fit:
//
// var d = request({url: "/api", verb: "POST"});
//   error: extra field \`verb\` doesn't appear in the row.

// If the body had read \`opts.method\`, the presence variable for
// \`method\` would be pinned to \`Pre\`, and the no-method call (\`a\`
// above) would fail to unify. Reading a field demands presence.
`,
            },
            {
                id: "classes",
                label: "classes.js",
                blurb: "Class bodies + private fields",
                expect: "ok",
                code: `// Class declarations desugar to factory functions returning a row of
// methods + fields. \`#name\` private fields lower to a sentinel key —
// unreachable from outside.

class Counter {
    #count = 0;
    inc() {
        this.#count = this.#count + 1;
        return this.#count;
    }
    get current() { return this.#count; }
}

var c = new Counter();
var n = c.inc();           // Number
var v = c.current;         // Number

// Try this — uncomment to see the parse error:
// var leak = c.#count;   // error!
`,
            },
            {
                id: "callable-rows",
                label: "callable-rows.js",
                blurb: "Functions are rows with statics",
                expect: "ok",
                code: `// Functions are *rows* — a call signature plus optional named fields.
// So \`String(42)\` and \`String.fromCharCode(65)\` are the same value
// used two different ways.

var c = String.fromCharCode(65);   // "A"
var s = String(42);                // "42"

var arr = [1, 2, 3];
var stringified = arr.map(String); // String[]

// Passing \`String\` where \`.map\` expects a function is pure row
// polymorphism — no special "constructor type" rule.
`,
            },
            {
                id: "higher-order",
                label: "higher-order.js",
                blurb: "First-class functions",
                expect: "ok",
                code: `// Functions are first-class. Inty handles higher-order use directly.

function compose(f, g) {
    return function(x) { return f(g(x)); };
}

function double(x) { return x * 2; }
function inc(x)    { return x + 1; }

var f = compose(double, inc);
var n = f(3);                       // (3 + 1) * 2 = 8

// \`compose\` is fully polymorphic — works for any matching pair.
var g = compose(function(s) { return s + "!"; },
                function(s) { return s + s; });
var loud = g("yo");                 // "yoyo!"
`,
            },
        ],
    },
    {
        id: "ts-misses",
        label: "TS wouldn't catch this",
        items: [
            {
                id: "string-plus-number",
                label: "string-plus-number.js",
                blurb: "`+` silently coerces in TS",
                expect: "error",
                code: `// TypeScript happily allows String + Number — JavaScript coerces,
// and so does the TS \`+\` rule. The intent is almost always wrong.
//
// Inty's \`Plus\` type class requires both operands to be the *same*
// instance: two Numbers, or two Strings. No silent coercion.

var count = 3;
var msg   = "Got " + count + " items";

// Inty: error — operands disagree.
// At runtime: "Got 3 items" (works by accident).
//
// The fix says what you mean:
//   var msg = "Got " + String(count) + " items";
`,
            },
            {
                id: "or-fallback",
                label: "or-fallback.js",
                blurb: "Truthy fallback hides type changes",
                expect: "ok",
                code: `// In JavaScript, \`||\` returns one of its operands — not a boolean.
// So \`0 || "Guest"\` evaluates to "Guest" and the variable's type
// silently widens to \`Number | String\`.
//
// TypeScript: tolerates the union without complaint.
// Inty: infers \`label(String) => String\` — calling with a Number
// fails at the call site, not silently inside the body.

function label(n) {
    var name = n || "Guest";        // n: Number, fallback: String — mismatch
    return name;
}

// Pass a Number to expose the bug:
// var r = label(3);   // error!

// Fix: make the default match the type, or convert explicitly.
//   var name = n === 0 ? "Guest" : String(n);
`,
            },
            {
                id: "mixed-array",
                label: "mixed-array.js",
                blurb: "Mixed arrays look uniform in TS",
                expect: "error",
                code: `// Without annotations, TypeScript widens this to \`(string | number)[]\`
// and lets you use any element as if it were either type.
// Inty types it as a closed union and forces a narrow before use.

var items = [1, "two", 3, "four"];

// In TS: items[0].toFixed(2) compiles (because of \`number\` in the union).
// At runtime: TypeError when the element is actually a string.
//
// Inty: \`.toFixed\` isn't on the union — you must narrow first.
function describe(x) {
    if (typeof x === "number") { return x.toFixed(2); }
    else                       { return x.toUpperCase(); }
}
var first = describe(items[0]);
`,
            },
            {
                id: "missing-prop",
                label: "missing-prop.js",
                blurb: "Reading a property that isn't there",
                expect: "error",
                code: `// Object literals produce *closed* rows in inty — what you wrote is
// all that's there. Reading a missing field is a structural error.
//
// In TypeScript without explicit types, this often types as \`any\`
// (via implicit-any or noImplicitAny=false) and slips through.

function fullName(user) {
    return user.firstName + " " + user.lastName;
}

var name = fullName({ name: "Alice", id: 42 });
//                        ^^^^^^^^^^^^^^^^^^
// Inty: \`firstName\` not found in \`{name: String, id: Number}\`.
// TS (.js, no types): silently \`any\` — caller sees no error.
`,
            },
            {
                id: "this-leak",
                label: "this-leak.js",
                blurb: "Methods called without their receiver",
                expect: "ok",
                code: `// Pulling a method off an object loses \`this\`. TypeScript with default
// settings types it as a plain function and lets you call it standalone.
// At runtime it explodes — \`this\` is undefined.
//
// Inty: \`this\` is part of the method's row type. The free function and
// the bound method aren't interchangeable.

var counter = {
    n: 0,
    inc: function() { this.n = this.n + 1; return this.n; }
};

var inc = counter.inc;
// var oops = inc();   // error!
// ↑ uncomment: at runtime, TypeError.
//   Inty rejects at type-check time.

var ok = counter.inc();
`,
            },
            {
                id: "truthy-narrow",
                label: "truthy-narrow.js",
                blurb: "0 and \"\" are falsy \u2014 silently",
                expect: "ok",
                code: `// JavaScript treats 0, "", NaN, null, undefined all as falsy.
// TypeScript's narrowing on \`if (x)\` doesn't distinguish between
// "missing" and "empty/zero" — easy bug.

function priceLabel(price) {
    if (price) { return "$" + price; }
    else       { return "free"; }
}

// Inty infers \`priceLabel(String) => String\` — the \`+\` inside fixes
// \`price\` to a String. Calling with the literal \`0\` then errors at
// the call site:
// var lbl = priceLabel(0);   // error!
//
// In TS, calling this with the literal \`0\` is fine — and silently
// returns "free" for a perfectly valid price of zero.
//
// The deeper fix — explicit \`price === undefined\` narrowing — is
// enforceable because inty types optional values as a real union.
`,
            },
        ],
    },
];

export function findExample(id) {
    for (const section of EXAMPLES) {
        for (const item of section.items) {
            if (item.id === id) return { section, item };
        }
    }
    return null;
}

export const DEFAULT_EXAMPLE_ID = "basics";
