//! AST → Go source.
//!
//! One pass over the checked AST. Every expression's Go type comes from
//! the type inty recorded for it during inference (keyed by span), so
//! the emitter never guesses: `a + b` becomes float64 addition or string
//! concatenation depending on what inty proved about `a` and `b`.
//!
//! Layout of the generated file:
//!
//! ```text
//! package main / imports
//! struct declarations      (one per object shape)
//! package-level vars       (top-level `var` / `let` / `const`)
//! top-level functions      (top-level `function` declarations)
//! func main()              (every other top-level statement, in order)
//! runtime helpers          (runtime.go)
//! ```

use std::collections::HashMap;

use inty::ast::free_idents::free_identifiers_in_stmt;
use inty::ast::*;
use inty::infer::InferState;
use inty::span::Span;
use inty::types::Type;

use crate::types::{GoType, TypeMapper};
use crate::{unsupported, Result};

const RUNTIME: &str = include_str!("runtime.go");

/// Emit a whole program. `state` must be the state that checked
/// `program`, with `expr_types` recording enabled.
pub fn emit_program(program: &Program, state: &mut InferState) -> Result<String> {
    let types = state
        .expr_types
        .take()
        .expect("inty-go: expression-type recording must be enabled before inference");
    let mut e = Emitter {
        state,
        types,
        tm: TypeMapper::default(),
        buf: String::new(),
        indent: 0,
        ret_stack: Vec::new(),
        tmp: 0,
        scopes: vec![HashMap::new()],
    };

    let mut globals = String::new();
    let mut funcs = String::new();
    let mut main_body = String::new();

    // Bind every top-level name first: function bodies may refer to
    // functions and variables declared further down (hoisting).
    for stmt in &program.statements {
        match stmt {
            Stmt::FunctionDecl { name, span, .. } => {
                let t = e.fn_type(*span)?;
                e.bind(name, t);
            }
            Stmt::Var { declarations, .. } => {
                for d in declarations {
                    let t = e.decl_type(d)?;
                    e.bind(&d.name, t);
                }
            }
            _ => {}
        }
    }

    // Pass 1: top-level functions become Go functions; top-level
    // variables become package-level vars so functions can see them.
    for stmt in &program.statements {
        match stmt {
            Stmt::FunctionDecl {
                name,
                params,
                body,
                span,
                ..
            } => {
                e.buf.clear();
                e.indent = 0;
                let (sig_params, ptys, ret) = e.signature(params, *span)?;
                e.line(&format!(
                    "func {}({}){} {{",
                    mangle(name),
                    sig_params,
                    e.tm.render_result(&ret)
                ));
                e.indent += 1;
                e.function_body(params, &ptys, body, &ret)?;
                e.indent -= 1;
                e.line("}");
                funcs.push_str(&e.buf);
                funcs.push('\n');
            }
            Stmt::Var { declarations, .. } => {
                for d in declarations {
                    let ty = e.decl_type(d)?;
                    globals.push_str(&format!("var {} {}\n", mangle(&d.name), e.tm.render(&ty)));
                }
            }
            _ => {}
        }
    }

    // Pass 2: everything else runs in `main`, in source order.
    e.buf.clear();
    e.indent = 1;
    e.ret_stack.push(GoType::Unit);
    for stmt in &program.statements {
        match stmt {
            Stmt::FunctionDecl { .. } => {}
            Stmt::Var { declarations, .. } => {
                for d in declarations {
                    if let Some(init) = &d.init {
                        let ty = e.decl_type(d)?;
                        let v = e.expr_as(init, &ty)?;
                        e.line(&format!("{} = {}", mangle(&d.name), v));
                    }
                }
            }
            other => e.stmt(other, &[])?,
        }
    }
    e.ret_stack.pop();
    main_body.push_str(&e.buf);

    let mut out = String::new();
    out.push_str("// Code generated by `inty go` from type-checked JavaScript. DO NOT EDIT.\n");
    out.push_str("// Requires Go >= 1.22 (per-iteration loop variables, like JS `let`).\n\n");
    out.push_str("package main\n\n");
    out.push_str(
        "import (\n\t\"bufio\"\n\t\"math\"\n\t\"math/bits\"\n\t\"math/rand\"\n\t\"os\"\n\t\"strconv\"\n\t\"strings\"\n\t\"time\"\n)\n\n",
    );
    out.push_str(&e.tm.render_structs());
    if !globals.is_empty() {
        out.push_str(&globals);
        out.push('\n');
    }
    out.push_str(&funcs);
    out.push_str("func main() {\n\tdefer intyOut.Flush()\n");
    out.push_str(&main_body);
    out.push_str("}\n\n");
    out.push_str(RUNTIME);
    Ok(out)
}

struct Emitter<'a> {
    state: &'a mut InferState,
    types: HashMap<(usize, usize), Type>,
    tm: TypeMapper,
    /// Statement output for the function currently being emitted.
    buf: String,
    indent: usize,
    /// Result type of each enclosing function (innermost last).
    ret_stack: Vec<GoType>,
    /// Counter for fresh temporaries.
    tmp: usize,
    /// Declared Go type of every JS binding in scope, innermost last.
    /// An identifier's type comes from here rather than from the type
    /// recorded at the use site: a use inside a hoisted function can be
    /// recorded as a structural *view* of the binding (e.g. an array seen
    /// as `{length: Number | ρ}`), which isn't the variable's Go type.
    scopes: Vec<HashMap<String, GoType>>,
}

/// A number the emitter can fold at translation time. Folding happens
/// in f64, matching JavaScript; Go would evaluate constant expressions
/// exactly (`0.1 + 0.2` is precisely `0.3` as a Go constant).
fn const_num(e: &Expr) -> Option<f64> {
    match e {
        Expr::Lit {
            value: Literal::Number(n),
            ..
        } => Some(*n),
        Expr::Unary {
            op: UnaryOp::Neg,
            argument,
            ..
        } => const_num(argument).map(|n| -n),
        Expr::Unary {
            op: UnaryOp::Pos,
            argument,
            ..
        } => const_num(argument),
        Expr::Binary {
            op, left, right, ..
        } => {
            let (a, b) = (const_num(left)?, const_num(right)?);
            Some(match op {
                BinOp::Add => a + b,
                BinOp::Sub => a - b,
                BinOp::Mul => a * b,
                BinOp::Div => a / b,
                BinOp::Mod => a % b,
                BinOp::Pow => a.powf(b),
                _ => return None,
            })
        }
        Expr::Member {
            object, property, ..
        } => match (&**object, property.as_str()) {
            (Expr::Ident { name, .. }, p) if name == "Math" => math_constant(p),
            (Expr::Ident { name, .. }, p) if name == "Number" => match p {
                "MAX_SAFE_INTEGER" => Some(9007199254740991.0),
                "MIN_SAFE_INTEGER" => Some(-9007199254740991.0),
                "EPSILON" => Some(f64::EPSILON),
                "MAX_VALUE" => Some(f64::MAX),
                "MIN_VALUE" => Some(5e-324),
                _ => None,
            },
            _ => None,
        },
        _ => None,
    }
}

fn math_constant(name: &str) -> Option<f64> {
    use std::f64::consts;
    Some(match name {
        "PI" => consts::PI,
        "E" => consts::E,
        "LN2" => consts::LN_2,
        "LN10" => consts::LN_10,
        "LOG2E" => consts::LOG2_E,
        "LOG10E" => consts::LOG10_E,
        "SQRT2" => consts::SQRT_2,
        _ => return None,
    })
}

/// Go spelling of a float64 value. Always carries a `.` or exponent so
/// the untyped constant defaults to float64, never int.
fn num_lit(n: f64) -> String {
    if n.is_nan() {
        "math.NaN()".into()
    } else if n.is_infinite() {
        if n > 0.0 {
            "math.Inf(1)"
        } else {
            "math.Inf(-1)"
        }
        .into()
    } else if n == 0.0 && n.is_sign_negative() {
        "math.Copysign(0, -1)".into()
    } else {
        // `{:?}` is the shortest round-trip form: `3.0`, `0.1`, `1e21`.
        let s = format!("{:?}", n);
        if n < 0.0 {
            format!("({})", s)
        } else {
            s
        }
    }
}

fn go_string_lit(s: &str) -> String {
    let mut out = String::from("\"");
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 || c as u32 == 0x7f => {
                out.push_str(&format!("\\x{:02x}", c as u32))
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

const GO_RESERVED: &[&str] = &[
    // keywords
    "break",
    "case",
    "chan",
    "const",
    "continue",
    "default",
    "defer",
    "else",
    "fallthrough",
    "for",
    "func",
    "go",
    "goto",
    "if",
    "import",
    "interface",
    "map",
    "package",
    "range",
    "return",
    "select",
    "struct",
    "switch",
    "type",
    "var",
    // predeclared identifiers
    "any",
    "append",
    "bool",
    "byte",
    "cap",
    "clear",
    "close",
    "comparable",
    "complex",
    "complex64",
    "complex128",
    "copy",
    "delete",
    "error",
    "false",
    "float32",
    "float64",
    "imag",
    "int",
    "int8",
    "int16",
    "int32",
    "int64",
    "iota",
    "len",
    "make",
    "max",
    "min",
    "new",
    "nil",
    "panic",
    "print",
    "println",
    "real",
    "recover",
    "rune",
    "string",
    "true",
    "uint",
    "uint8",
    "uint16",
    "uint32",
    "uint64",
    "uintptr",
    // imported packages and entry points
    "bufio",
    "math",
    "bits",
    "rand",
    "os",
    "strconv",
    "strings",
    "time",
    "main",
    "init",
];

/// Go identifier for a JS identifier or property name. Collisions with
/// Go keywords, predeclared names, imported packages and the emitter's
/// own namespaces (`inty*` helpers, `ObjN` structs) get a trailing `_`.
pub fn mangle(name: &str) -> String {
    let mut s = String::new();
    for c in name.chars() {
        if c.is_alphanumeric() || c == '_' {
            s.push(c);
        } else if c == '$' {
            s.push_str("_S");
        } else {
            s.push_str(&format!("_x{:x}", c as u32));
        }
    }
    if s.is_empty() || s.starts_with(|c: char| c.is_ascii_digit()) || s == "_" {
        s.insert(0, '_');
        s.push('_');
    }
    let is_obj = s
        .strip_prefix("Obj")
        .is_some_and(|r| !r.is_empty() && r.chars().all(|c| c.is_ascii_digit()));
    if GO_RESERVED.contains(&s.as_str()) || s.starts_with("inty") || is_obj {
        s.push('_');
    }
    s
}

/// Whether evaluating `e` twice is indistinguishable from once — used
/// before expanding compound assignments that Go can't express directly.
fn is_pure_place(e: &Expr) -> bool {
    match e {
        Expr::Ident { .. } | Expr::Lit { .. } | Expr::This { .. } => true,
        Expr::Member { object, .. } => is_pure_place(object),
        Expr::ComputedMember {
            object, property, ..
        } => is_pure_place(object) && is_pure_place(property),
        _ => false,
    }
}

fn is_terminator(s: &Stmt) -> bool {
    match s {
        Stmt::Break { .. } | Stmt::Continue { .. } | Stmt::Return { .. } | Stmt::Throw { .. } => {
            true
        }
        Stmt::Block { body, .. } => body.last().is_some_and(is_terminator),
        _ => false,
    }
}

impl<'a> Emitter<'a> {
    // ---- output ----------------------------------------------------------

    fn line(&mut self, s: &str) {
        for _ in 0..self.indent {
            self.buf.push('\t');
        }
        self.buf.push_str(s);
        self.buf.push('\n');
    }

    fn pad(&self) -> String {
        "\t".repeat(self.indent)
    }

    fn fresh(&mut self, stem: &str) -> String {
        self.tmp += 1;
        format!("inty{}{}", stem, self.tmp)
    }

    /// Emit statements into a detached buffer one level deeper and
    /// return the text — used for function literals inside expressions.
    fn nested<F>(&mut self, f: F) -> Result<String>
    where
        F: FnOnce(&mut Self) -> Result<()>,
    {
        let saved = std::mem::take(&mut self.buf);
        self.indent += 1;
        let r = f(self);
        self.indent -= 1;
        let body = std::mem::replace(&mut self.buf, saved);
        r.map(|()| body)
    }

    // ---- types -----------------------------------------------------------

    /// The fully-resolved type inty recorded for the node at `span`.
    fn raw_type(&mut self, span: Span) -> Result<Type> {
        match self.types.get(&(span.start, span.end)) {
            Some(t) => Ok(crate::types::resolve(self.state, t)),
            None => Err(unsupported("expression with no recorded type", span)),
        }
    }

    fn bind(&mut self, name: &str, t: GoType) {
        self.scopes.last_mut().expect("scope").insert(name.to_string(), t);
    }

    fn lookup(&self, name: &str) -> Option<&GoType> {
        self.scopes.iter().rev().find_map(|s| s.get(name))
    }

    fn fn_type(&mut self, span: Span) -> Result<GoType> {
        let t = self.raw_type(span)?;
        self.tm.map(self.state, &t, span)
    }

    fn type_of(&mut self, e: &Expr) -> Result<GoType> {
        if let Expr::Ident { name, .. } = e {
            if let Some(t) = self.lookup(name) {
                return Ok(t.clone());
            }
        }
        let span = e.span();
        let t = self.raw_type(span)?;
        self.tm.map(self.state, &t, span)
    }

    fn decl_type(&mut self, d: &VarDeclarator) -> Result<GoType> {
        if let Some(t) = self.state.get_decl_type(d.span).cloned() {
            let t = crate::types::resolve(self.state, &t);
            return self.tm.map(self.state, &t, d.span);
        }
        match &d.init {
            Some(init) => self.type_of(init),
            None => Err(unsupported("declaration without an inferred type", d.span)),
        }
    }

    /// Go parameter list and result type for a function at `span`.
    fn signature(&mut self, params: &[Param], span: Span) -> Result<(String, Vec<GoType>, GoType)> {
        let t = self.raw_type(span)?;
        let (ps, ret) = match self.tm.map(self.state, &t, span)? {
            GoType::Func(ps, ret) => (ps, *ret),
            other => {
                return Err(unsupported(
                    format!("function whose type maps to {}", self.tm.render(&other)),
                    span,
                ))
            }
        };
        if ps.len() != params.len() {
            return Err(unsupported("optional or defaulted parameters", span));
        }
        let rendered: Vec<String> = params
            .iter()
            .zip(&ps)
            .map(|(p, t)| format!("{} {}", mangle(&p.name), self.tm.render(t)))
            .collect();
        Ok((rendered.join(", "), ps, ret))
    }

    fn function_body(&mut self, params: &[Param], ptys: &[GoType], body: &Stmt, ret: &GoType) -> Result<()> {
        self.scopes.push(HashMap::new());
        for (p, t) in params.iter().zip(ptys) {
            self.bind(&p.name, t.clone());
        }
        self.ret_stack.push(ret.clone());
        let stmts: &[Stmt] = match body {
            Stmt::Block { body, .. } => body,
            other => std::slice::from_ref(other),
        };
        self.block_stmts(stmts)?;
        if *ret != GoType::Unit && !stmts.last().is_some_and(is_terminator) {
            // inty proved control can't fall off the end (otherwise the
            // result type would include `undefined`); Go's syntactic
            // terminating-statement check can't always see that.
            self.line("panic(\"unreachable\")");
        }
        self.ret_stack.pop();
        self.scopes.pop();
        Ok(())
    }

    fn func_literal(&mut self, params: &[Param], body: &Stmt, span: Span) -> Result<String> {
        let (sig, ptys, ret) = self.signature(params, span)?;
        let text = self.nested(|e| e.function_body(params, &ptys, body, &ret))?;
        Ok(format!(
            "func({}){} {{\n{}{}}}",
            sig,
            self.tm.render_result(&ret),
            text,
            self.pad()
        ))
    }

    // ---- statements --------------------------------------------------------

    /// Emit a statement list that forms one Go block. Nested function
    /// declarations are declared up front (JS hoists them).
    fn block_stmts(&mut self, stmts: &[Stmt]) -> Result<()> {
        self.scopes.push(HashMap::new());
        let r = self.block_stmts_in_scope(stmts);
        self.scopes.pop();
        r
    }

    fn block_stmts_in_scope(&mut self, stmts: &[Stmt]) -> Result<()> {
        for s in stmts {
            if let Stmt::FunctionDecl { name, span, .. } = s {
                let g = self.fn_type(*span)?;
                let rendered = self.tm.render(&g);
                self.line(&format!("var {} {}", mangle(name), rendered));
                self.bind(name, g);
            }
        }
        for (i, s) in stmts.iter().enumerate() {
            self.stmt(s, &stmts[i + 1..])?;
        }
        Ok(())
    }

    fn stmt(&mut self, s: &Stmt, rest: &[Stmt]) -> Result<()> {
        match s {
            Stmt::Empty { .. } => {}
            Stmt::Block { body, .. } => {
                self.line("{");
                self.indent += 1;
                self.block_stmts(body)?;
                self.indent -= 1;
                self.line("}");
            }
            Stmt::Expr { expression, .. } => self.expr_stmt(expression)?,
            Stmt::Var { declarations, .. } => {
                for (i, d) in declarations.iter().enumerate() {
                    let ty = self.decl_type(d)?;
                    let name = mangle(&d.name);
                    let rendered = self.tm.render(&ty);
                    match &d.init {
                        // A function value may refer to itself: declare
                        // first so the literal can capture the variable.
                        Some(init @ Expr::Function { .. }) => {
                            self.line(&format!("var {} {}", name, rendered));
                            self.bind(&d.name, ty.clone());
                            let v = self.expr(init)?;
                            self.line(&format!("{} = {}", name, v));
                        }
                        Some(init) => {
                            let v = self.expr_as(init, &ty)?;
                            self.line(&format!("var {} {} = {}", name, rendered, v));
                        }
                        None => self.line(&format!("var {} {}", name, rendered)),
                    }
                    self.bind(&d.name, ty.clone());
                    // Go rejects unused locals; JS doesn't care.
                    let used_later = declarations[i + 1..]
                        .iter()
                        .filter_map(|d| d.init.as_ref())
                        .any(|e| {
                            inty::ast::free_idents::free_identifiers_in_expr(e).contains(&d.name)
                        })
                        || rest
                            .iter()
                            .any(|s| free_identifiers_in_stmt(s).contains(&d.name));
                    if !used_later {
                        self.line(&format!("_ = {}", name));
                    }
                }
            }
            Stmt::FunctionDecl {
                name,
                params,
                body,
                span,
                ..
            } => {
                // Declared by `block_stmts`; assign here.
                let f = self.func_literal(params, body, *span)?;
                self.line(&format!("{} = {}", mangle(name), f));
            }
            Stmt::Return { argument, span } => {
                let ret = self.ret_stack.last().cloned().unwrap_or(GoType::Unit);
                match (argument, &ret) {
                    (None, _) => self.line("return"),
                    (Some(a), GoType::Unit) => {
                        return Err(unsupported(
                            "returning a value of type undefined",
                            a.span().merge(*span),
                        ))
                    }
                    (Some(a), ret) => {
                        let v = self.expr_as(a, ret)?;
                        self.line(&format!("return {}", v));
                    }
                }
            }
            Stmt::If {
                test,
                consequent,
                alternate,
                ..
            } => {
                let c = self.cond(test)?;
                self.line(&format!("if {} {{", c));
                self.sub_block(consequent)?;
                let mut alt = alternate.as_deref();
                while let Some(a) = alt {
                    match a {
                        Stmt::If {
                            test,
                            consequent,
                            alternate,
                            ..
                        } => {
                            let c = self.cond(test)?;
                            self.line(&format!("}} else if {} {{", c));
                            self.sub_block(consequent)?;
                            alt = alternate.as_deref();
                        }
                        other => {
                            self.line("} else {");
                            self.sub_block(other)?;
                            alt = None;
                        }
                    }
                }
                self.line("}");
            }
            Stmt::While { test, body, .. } => {
                if matches!(
                    test,
                    Expr::Lit {
                        value: Literal::Boolean(true),
                        ..
                    }
                ) {
                    self.line("for {");
                } else {
                    let c = self.cond(test)?;
                    self.line(&format!("for {} {{", c));
                }
                self.sub_block(body)?;
                self.line("}");
            }
            Stmt::DoWhile { body, test, .. } => {
                // `continue` must still evaluate the test, which is what
                // a Go `for` post statement + condition gives us.
                let first = self.fresh("First");
                let c = self.cond(test)?;
                self.line(&format!(
                    "for {first} := true; {first} || {c}; {first} = false {{"
                ));
                self.sub_block(body)?;
                self.line("}");
            }
            Stmt::For {
                init,
                test,
                update,
                body,
                span,
            } => self.for_stmt(init.as_ref(), test.as_ref(), update.as_ref(), body, *span)?,
            Stmt::ForOf {
                left, right, body, ..
            } => {
                let elem = match self.type_of(right)? {
                    GoType::Array(e) => *e,
                    _ => return Err(unsupported("for-of over a non-array", right.span())),
                };
                self.scopes.push(HashMap::new());
                let arr = self.fresh("Arr");
                let idx = self.fresh("I");
                let a = self.expr(right)?;
                self.line("{");
                self.indent += 1;
                self.line(&format!("{arr} := {a}"));
                self.line(&format!("for {idx} := 0; {idx} < len(*{arr}); {idx}++ {{"));
                self.indent += 1;
                match left {
                    ForInLhs::VarDecl(name, _, _) => {
                        let n = mangle(name);
                        let t = self.tm.render(&elem);
                        self.line(&format!("var {n} {t} = (*{arr})[{idx}]"));
                        self.line(&format!("_ = {n}"));
                        self.bind(name, elem.clone());
                    }
                    ForInLhs::Expr(target) => {
                        let place = self.place(target)?;
                        self.line(&format!("{place} = (*{arr})[{idx}]"));
                    }
                }
                self.block_body(body)?;
                self.indent -= 1;
                self.line("}");
                self.indent -= 1;
                self.line("}");
                self.scopes.pop();
            }
            Stmt::Break { label, .. } => match label {
                Some(l) => self.line(&format!("break {}", mangle(l))),
                None => self.line("break"),
            },
            Stmt::Continue { label, .. } => match label {
                Some(l) => self.line(&format!("continue {}", mangle(l))),
                None => self.line("continue"),
            },
            Stmt::Labeled { label, body, .. } => {
                let saved = self.indent;
                self.indent = self.indent.saturating_sub(1);
                self.line(&format!("{}:", mangle(label)));
                self.indent = saved;
                self.stmt(body, rest)?;
            }
            Stmt::Switch {
                discriminant,
                cases,
                span,
            } => self.switch_stmt(discriminant, cases, *span)?,
            Stmt::Throw { span, .. } => return Err(unsupported("throw", *span)),
            Stmt::Try { span, .. } => return Err(unsupported("try/catch", *span)),
            Stmt::ForIn { span, .. } => return Err(unsupported("for-in", *span)),
            Stmt::Import { span, .. } | Stmt::Export { span, .. } => {
                return Err(unsupported("ES modules (single-file programs only)", *span))
            }
        }
        Ok(())
    }

    /// The body of a compound statement, as the contents of a Go block.
    fn sub_block(&mut self, s: &Stmt) -> Result<()> {
        self.indent += 1;
        self.block_body(s)?;
        self.indent -= 1;
        Ok(())
    }

    fn block_body(&mut self, s: &Stmt) -> Result<()> {
        match s {
            Stmt::Block { body, .. } => self.block_stmts(body),
            other => self.block_stmts(std::slice::from_ref(other)),
        }
    }

    fn for_stmt(
        &mut self,
        init: Option<&ForInit>,
        test: Option<&Expr>,
        update: Option<&Expr>,
        body: &Stmt,
        _span: Span,
    ) -> Result<()> {
        self.scopes.push(HashMap::new());
        let r = self.for_stmt_in_scope(init, test, update, body);
        self.scopes.pop();
        r
    }

    fn for_stmt_in_scope(
        &mut self,
        init: Option<&ForInit>,
        test: Option<&Expr>,
        update: Option<&Expr>,
        body: &Stmt,
    ) -> Result<()> {
        let mut pre = Vec::new();
        let init_s = match init {
            None => String::new(),
            Some(ForInit::Expr(e)) => self.simple_stmt(e)?,
            Some(ForInit::VarDecl(decls)) => {
                // `let` in a for header is per-iteration in JS and (since
                // Go 1.22) in Go, so `:=` in the init clause matches.
                let mut names = Vec::new();
                let mut vals = Vec::new();
                for d in decls {
                    let ty = self.decl_type(d)?;
                    let v = match &d.init {
                        Some(init) => self.expr_as(init, &ty)?,
                        None => return Err(unsupported("uninitialised for-loop variable", d.span)),
                    };
                    let v = match &ty {
                        GoType::Float | GoType::Str | GoType::Bool => v,
                        _ if v == "nil" => {
                            return Err(unsupported("null-initialised for-loop variable", d.span))
                        }
                        _ => v,
                    };
                    names.push(mangle(&d.name));
                    vals.push(v);
                    pre.push(d.name.clone());
                    self.bind(&d.name, ty);
                }
                format!("{} := {}", names.join(", "), vals.join(", "))
            }
        };
        let test_s = match test {
            Some(t) => self.cond(t)?,
            None => String::new(),
        };
        let update_s = match update {
            Some(u) => self.simple_stmt(u)?,
            None => String::new(),
        };
        if init_s.is_empty() && update_s.is_empty() {
            if test_s.is_empty() {
                self.line("for {");
            } else {
                self.line(&format!("for {} {{", test_s));
            }
        } else {
            self.line(&format!("for {}; {}; {} {{", init_s, test_s, update_s));
        }
        self.indent += 1;
        // A header variable nothing reads would be a Go compile error.
        for name in &pre {
            let used = test.is_some_and(|t| {
                inty::ast::free_idents::free_identifiers_in_expr(t).contains(name)
            }) || update.is_some_and(|u| {
                inty::ast::free_idents::free_identifiers_in_expr(u).contains(name)
            }) || free_identifiers_in_stmt(body).contains(name);
            if !used {
                self.line(&format!("_ = {}", mangle(name)));
            }
        }
        self.block_body(body)?;
        self.indent -= 1;
        self.line("}");
        Ok(())
    }

    fn switch_stmt(&mut self, disc: &Expr, cases: &[SwitchCase], _span: Span) -> Result<()> {
        let dt = self.type_of(disc)?;
        let d = self.expr(disc)?;
        self.line(&format!("switch {} {{", d));
        let mut pending: Vec<String> = Vec::new();
        for (i, case) in cases.iter().enumerate() {
            match &case.test {
                Some(t) => {
                    let v = self.expr_as(t, &dt)?;
                    pending.push(v);
                }
                None if !pending.is_empty() => {
                    return Err(unsupported("`case` falling into `default`", case.span))
                }
                None => {}
            }
            if case.consequent.is_empty() && i + 1 < cases.len() {
                continue; // grouped labels: `case 1: case 2: ...`
            }
            if case.test.is_none() {
                self.line("default:");
            } else {
                self.line(&format!("case {}:", pending.join(", ")));
            }
            pending.clear();
            self.indent += 1;
            let mut body: &[Stmt] = &case.consequent;
            if let Some(Stmt::Break { label: None, .. }) = body.last() {
                body = &body[..body.len() - 1];
            }
            // Block-scoped declarations in a case need their own scope
            // in Go only if they'd collide; the case clause already is one.
            self.block_stmts(body)?;
            let ends = case.consequent.last().is_some_and(is_terminator);
            if !ends && i + 1 < cases.len() {
                self.line("fallthrough");
            }
            self.indent -= 1;
        }
        self.line("}");
        Ok(())
    }

    /// An expression in statement position.
    fn expr_stmt(&mut self, e: &Expr) -> Result<()> {
        match e {
            Expr::Conditional {
                test,
                consequent,
                alternate,
                ..
            } => {
                let c = self.cond(test)?;
                self.line(&format!("if {} {{", c));
                self.indent += 1;
                self.expr_stmt(consequent)?;
                self.indent -= 1;
                self.line("} else {");
                self.indent += 1;
                self.expr_stmt(alternate)?;
                self.indent -= 1;
                self.line("}");
            }
            Expr::Binary {
                op: op @ (BinOp::And | BinOp::Or),
                left,
                right,
                ..
            } => {
                let c = self.cond(left)?;
                let c = if *op == BinOp::And {
                    c
                } else {
                    format!("!{}", c)
                };
                self.line(&format!("if {} {{", c));
                self.indent += 1;
                self.expr_stmt(right)?;
                self.indent -= 1;
                self.line("}");
            }
            Expr::Sequence { expressions, .. } => {
                for x in expressions {
                    self.expr_stmt(x)?;
                }
            }
            _ => {
                let s = self.simple_stmt(e)?;
                self.line(&s);
            }
        }
        Ok(())
    }

    /// A Go "simple statement" (assignment, inc/dec, call) for `e`.
    fn simple_stmt(&mut self, e: &Expr) -> Result<String> {
        match e {
            Expr::Assign {
                op, left, right, ..
            } => self.assign_stmt(*op, left, right),
            Expr::Unary {
                op: op @ (UnaryOp::PreInc | UnaryOp::PostInc | UnaryOp::PreDec | UnaryOp::PostDec),
                argument,
                ..
            } => {
                let p = self.place(argument)?;
                let inc = matches!(op, UnaryOp::PreInc | UnaryOp::PostInc);
                Ok(format!("{}{}", p, if inc { "++" } else { "--" }))
            }
            Expr::Call {
                callee,
                arguments,
                span,
                ..
            } => {
                // `arr.push(x)` as a statement: append in place.
                if let Expr::Member {
                    object, property, ..
                } = &**callee
                {
                    if property == "push" && arguments.len() == 1 && is_pure_place(object) {
                        if let GoType::Array(elem) = self.type_of(object)? {
                            let a = self.expr(object)?;
                            let v = self.expr_as(&arguments[0], &elem)?;
                            return Ok(format!("*{a} = append(*{a}, {v})"));
                        }
                    }
                }
                self.call(callee, arguments, *span, true)
            }
            other => {
                let v = self.expr(other)?;
                Ok(format!("_ = {}", v))
            }
        }
    }

    fn assign_stmt(&mut self, op: AssignOp, left: &Expr, right: &Expr) -> Result<String> {
        let lt = self.type_of(left)?;
        // Plain element store: JS grows the array on `a[a.length] = v`.
        if op == AssignOp::Assign {
            if let Expr::ComputedMember {
                object, property, ..
            } = left
            {
                if let GoType::Array(elem) = self.type_of(object)? {
                    let a = self.expr(object)?;
                    let i = self.expr(property)?;
                    let v = self.expr_as(right, &elem)?;
                    return Ok(format!("intySet({a}, {i}, {v})"));
                }
            }
        }
        let p = self.place(left)?;
        let r = self.expr_as(right, &lt)?;
        let direct = |o: &str| Ok(format!("{} {} {}", p, o, r));
        match op {
            AssignOp::Assign => direct("="),
            AssignOp::AddAssign if lt == GoType::Str => direct("+="),
            AssignOp::AddAssign => direct("+="),
            AssignOp::SubAssign => direct("-="),
            AssignOp::MulAssign => direct("*="),
            AssignOp::DivAssign if const_num(right) == Some(0.0) => {
                Ok(format!("{} /= intyZero", p))
            }
            AssignOp::DivAssign => direct("/="),
            _ => {
                if !is_pure_place(left) {
                    return Err(unsupported(
                        "compound assignment to a place with side effects",
                        left.span(),
                    ));
                }
                let v = match op {
                    AssignOp::ModAssign => format!("intyMod({p}, {r})"),
                    AssignOp::PowAssign => format!("intyPow({p}, {r})"),
                    AssignOp::BitAndAssign => {
                        format!("float64(intyToInt32({p}) & intyToInt32({r}))")
                    }
                    AssignOp::BitOrAssign => {
                        format!("float64(intyToInt32({p}) | intyToInt32({r}))")
                    }
                    AssignOp::BitXorAssign => {
                        format!("float64(intyToInt32({p}) ^ intyToInt32({r}))")
                    }
                    AssignOp::LShiftAssign => {
                        format!("float64(intyToInt32({p}) << (intyToUint32({r}) & 31))")
                    }
                    AssignOp::RShiftAssign => {
                        format!("float64(intyToInt32({p}) >> (intyToUint32({r}) & 31))")
                    }
                    AssignOp::URShiftAssign => {
                        format!("float64(intyToUint32({p}) >> (intyToUint32({r}) & 31))")
                    }
                    _ => return Err(unsupported("logical assignment operator", left.span())),
                };
                Ok(format!("{} = {}", p, v))
            }
        }
    }

    /// An assignable Go expression for `e`.
    fn place(&mut self, e: &Expr) -> Result<String> {
        match e {
            Expr::Ident { .. } | Expr::Member { .. } => self.expr(e),
            Expr::ComputedMember {
                object, property, ..
            } => match self.type_of(object)? {
                GoType::Array(_) => {
                    let a = self.expr(object)?;
                    let i = self.index(property)?;
                    Ok(format!("(*{})[{}]", a, i))
                }
                _ => Err(unsupported("indexed assignment to a non-array", e.span())),
            },
            _ => Err(unsupported("assignment target", e.span())),
        }
    }

    // ---- expressions ---------------------------------------------------

    /// A Go `bool` for a JS condition, applying JS truthiness.
    fn cond(&mut self, e: &Expr) -> Result<String> {
        let t = self.type_of(e)?;
        let v = self.expr(e)?;
        self.truthy(v, &t, e.span())
    }

    fn truthy(&self, v: String, t: &GoType, span: Span) -> Result<String> {
        Ok(match t {
            GoType::Bool => v,
            GoType::Float => format!("intyTruthy({})", v),
            GoType::Str => format!("({} != \"\")", v),
            GoType::Array(_) | GoType::Struct(_) | GoType::Func(..) => format!("({} != nil)", v),
            _ => return Err(unsupported("condition of this type", span)),
        })
    }

    /// Index expression for a slice.
    fn index(&mut self, e: &Expr) -> Result<String> {
        if let Some(n) = const_num(e) {
            if n >= 0.0 && n.fract() == 0.0 && n < 1e15 {
                return Ok(format!("{}", n as i64));
            }
        }
        let v = self.expr(e)?;
        Ok(format!("int({})", v))
    }

    /// `e`, where the context expects a value of type `want`. Only
    /// differs from [`Self::expr`] for `null`/`undefined`, whose own
    /// recorded type says nothing about which Go type the nil is.
    fn expr_as(&mut self, e: &Expr, want: &GoType) -> Result<String> {
        match e {
            Expr::Lit {
                value: Literal::Null | Literal::Undefined,
                span,
            } => {
                if want.is_nullable() {
                    Ok("nil".into())
                } else {
                    Err(unsupported(
                        "null/undefined where a primitive is expected",
                        *span,
                    ))
                }
            }
            Expr::Ident { name, span } if name == "undefined" => {
                if want.is_nullable() {
                    Ok("nil".into())
                } else {
                    Err(unsupported(
                        "undefined where a primitive is expected",
                        *span,
                    ))
                }
            }
            _ => self.expr(e),
        }
    }

    fn to_str(&mut self, v: String, t: &GoType, span: Span) -> Result<String> {
        Ok(match t {
            GoType::Str => v,
            GoType::Float => format!("intyNumStr({})", v),
            GoType::Bool => format!("intyBoolStr({})", v),
            GoType::Array(elem) => {
                let f = self.str_func(elem, span)?;
                format!("intyJoin({}, \",\", {})", v, f)
            }
            _ => return Err(unsupported("string conversion of this type", span)),
        })
    }

    /// A Go func value converting `t` to a string (for `join`).
    fn str_func(&mut self, t: &GoType, span: Span) -> Result<String> {
        Ok(match t {
            GoType::Str => "func(s string) string { return s }".into(),
            GoType::Float => "intyNumStr".into(),
            GoType::Bool => "intyBoolStr".into(),
            _ => return Err(unsupported("join over elements of this type", span)),
        })
    }

    fn expr(&mut self, e: &Expr) -> Result<String> {
        if let Some(n) = const_num(e) {
            return Ok(num_lit(n));
        }
        match e {
            Expr::Lit { value, span } => match value {
                Literal::Number(n) => Ok(num_lit(*n)),
                Literal::String(s) => Ok(go_string_lit(s)),
                Literal::Boolean(b) => Ok(b.to_string()),
                Literal::Null | Literal::Undefined => Ok("nil".into()),
                Literal::Regex { .. } => Err(unsupported("regular expression", *span)),
            },
            Expr::Ident { name, span } => match name.as_str() {
                "NaN" => Ok("math.NaN()".into()),
                "Infinity" => Ok("math.Inf(1)".into()),
                "undefined" => Ok("nil".into()),
                _ => {
                    let _ = span;
                    Ok(mangle(name))
                }
            },
            Expr::This { span } => Err(unsupported("`this`", *span)),
            Expr::Array { elements, span } => {
                let elem = match self.type_of(e)? {
                    GoType::Array(el) => *el,
                    _ => return Err(unsupported("array literal of non-array type", *span)),
                };
                let mut items = Vec::new();
                for el in elements {
                    match el {
                        None => return Err(unsupported("array hole", *span)),
                        Some(Expr::Spread { span, .. }) => {
                            return Err(unsupported("array spread", *span))
                        }
                        Some(x) => items.push(self.expr_as(x, &elem)?),
                    }
                }
                let t = self.tm.render(&elem);
                if items.len() > 2 {
                    let pad = self.pad();
                    let inner: Vec<String> =
                        items.iter().map(|i| format!("{pad}\t{i},\n")).collect();
                    Ok(format!("&[]{}{{\n{}{}}}", t, inner.concat(), pad))
                } else {
                    Ok(format!("&[]{}{{{}}}", t, items.join(", ")))
                }
            }
            Expr::Object { properties, span } => {
                let idx = match self.type_of(e)? {
                    GoType::Struct(i) => i,
                    _ => return Err(unsupported("object literal of this type", *span)),
                };
                let mut fields = Vec::new();
                for p in properties {
                    match p {
                        PropDef::Property { key, value, .. } => {
                            let k = match key {
                                PropKey::Ident(s) | PropKey::String(s) => s.clone(),
                                PropKey::Number(n) => format!("{}", n),
                            };
                            let (_, go, ft) = self.tm.field(idx, &k).cloned().ok_or_else(|| {
                                unsupported("object field missing from its type", *span)
                            })?;
                            let v = self.expr_as(value, &ft)?;
                            fields.push(format!("{}: {}", go, v));
                        }
                        PropDef::Method {
                            key,
                            params,
                            body,
                            span,
                            ..
                        } => {
                            let k = match key {
                                PropKey::Ident(s) | PropKey::String(s) => s.clone(),
                                PropKey::Number(n) => format!("{}", n),
                            };
                            let go =
                                self.tm.field(idx, &k).map(|f| f.1.clone()).ok_or_else(|| {
                                    unsupported("method missing from its type", *span)
                                })?;
                            let f = self.func_literal(params, body, *span)?;
                            fields.push(format!("{}: {}", go, f));
                        }
                        PropDef::Getter { span, .. } | PropDef::Setter { span, .. } => {
                            return Err(unsupported("getter/setter", *span))
                        }
                        PropDef::Spread { span, .. } => {
                            return Err(unsupported("object spread", *span))
                        }
                    }
                }
                let name = self.tm.structs[idx].name.clone();
                Ok(format!("&{}{{{}}}", name, fields.join(", ")))
            }
            Expr::Function {
                name,
                params,
                body,
                span,
                ..
            } => {
                if name.is_some() {
                    return Err(unsupported("named function expression", *span));
                }
                self.func_literal(params, body, *span)
            }
            Expr::Member {
                object,
                property,
                span,
            } => self.member(object, property, *span),
            Expr::ComputedMember {
                object,
                property,
                span,
            } => match self.type_of(object)? {
                GoType::Array(_) => {
                    let a = self.expr(object)?;
                    let i = self.index(property)?;
                    Ok(format!("(*{})[{}]", a, i))
                }
                GoType::Str => {
                    let s = self.expr(object)?;
                    let i = self.index(property)?;
                    Ok(format!("string({}[{}])", s, i))
                }
                _ => Err(unsupported("computed member access on this type", *span)),
            },
            Expr::Call {
                callee,
                arguments,
                span,
                ..
            } => self.call(callee, arguments, *span, false),
            Expr::Unary { op, argument, span } => self.unary(*op, argument, *span, e),
            Expr::Binary {
                op,
                left,
                right,
                span,
            } => self.binary(*op, left, right, *span),
            Expr::Assign { .. } => {
                // Assignment used as a value: run it, then read it back.
                let t = self.type_of(e)?;
                let Expr::Assign { left, .. } = e else {
                    unreachable!()
                };
                if !is_pure_place(left) {
                    return Err(unsupported(
                        "assignment expression with side-effecting target",
                        e.span(),
                    ));
                }
                let s = self.simple_stmt(e)?;
                let p = self.place(left)?;
                Ok(format!(
                    "func() {} {{ {}; return {} }}()",
                    self.tm.render(&t),
                    s,
                    p
                ))
            }
            Expr::Conditional {
                test,
                consequent,
                alternate,
                ..
            } => {
                let t = self.type_of(e)?;
                let c = self.cond(test)?;
                let a = self.expr_as(consequent, &t)?;
                let b = self.expr_as(alternate, &t)?;
                Ok(format!(
                    "func() {} {{\n{p}\tif {} {{\n{p}\t\treturn {}\n{p}\t}}\n{p}\treturn {}\n{p}}}()",
                    self.tm.render(&t),
                    c,
                    a,
                    b,
                    p = self.pad()
                ))
            }
            Expr::TemplateLiteral {
                quasis,
                expressions,
                span,
            } => {
                let mut parts = Vec::new();
                for (i, q) in quasis.iter().enumerate() {
                    if !q.is_empty() {
                        parts.push(go_string_lit(q));
                    }
                    if let Some(x) = expressions.get(i) {
                        let t = self.type_of(x)?;
                        let v = self.expr(x)?;
                        parts.push(self.to_str(v, &t, *span)?);
                    }
                }
                if parts.is_empty() {
                    Ok("\"\"".into())
                } else {
                    Ok(format!("({})", parts.join(" + ")))
                }
            }
            Expr::Tuple { span, .. } => Err(unsupported("tuple", *span)),
            Expr::New { span, .. } => Err(unsupported("`new`", *span)),
            Expr::NewTarget { span } => Err(unsupported("new.target", *span)),
            Expr::NullishCoalesce { span, .. } => Err(unsupported("`??`", *span)),
            Expr::OptionalChain { span, .. } => Err(unsupported("optional chaining", *span)),
            Expr::Spread { span, .. } => Err(unsupported("spread", *span)),
            Expr::RestArray { span, .. } | Expr::RestRow { span, .. } => {
                Err(unsupported("destructuring rest pattern", *span))
            }
            Expr::Sequence { span, .. } => Err(unsupported("comma operator", *span)),
        }
    }

    fn member(&mut self, object: &Expr, property: &str, span: Span) -> Result<String> {
        match self.type_of(object)? {
            GoType::Array(_) if property == "length" => {
                let a = self.expr(object)?;
                Ok(format!("float64(len(*{}))", a))
            }
            GoType::Str if property == "length" => {
                let s = self.expr(object)?;
                Ok(format!("float64(len({}))", s))
            }
            GoType::Struct(idx) => {
                let go = self
                    .tm
                    .field(idx, property)
                    .map(|f| f.1.clone())
                    .ok_or_else(|| unsupported(format!("property `{}`", property), span))?;
                let o = self.expr(object)?;
                Ok(format!("{}.{}", o, go))
            }
            _ => Err(unsupported(
                format!("property `.{}` on this type", property),
                span,
            )),
        }
    }

    fn unary(&mut self, op: UnaryOp, arg: &Expr, span: Span, whole: &Expr) -> Result<String> {
        let t = self.type_of(arg)?;
        match op {
            UnaryOp::Neg if t == GoType::Float => Ok(format!("(-{})", self.expr(arg)?)),
            UnaryOp::Pos if t == GoType::Float => self.expr(arg),
            UnaryOp::Not => {
                let v = self.expr(arg)?;
                let c = self.truthy(v, &t, span)?;
                Ok(format!("(!{})", c))
            }
            UnaryOp::BitNot => Ok(format!("float64(^intyToInt32({}))", self.expr(arg)?)),
            UnaryOp::Typeof if matches!(arg, Expr::Ident { .. }) => Ok(go_string_lit(match t {
                GoType::Float => "number",
                GoType::Str => "string",
                GoType::Bool => "boolean",
                GoType::Func(..) => "function",
                GoType::Unit => "undefined",
                _ => "object",
            })),
            UnaryOp::PreInc | UnaryOp::PreDec | UnaryOp::PostInc | UnaryOp::PostDec => {
                if !is_pure_place(arg) {
                    return Err(unsupported("update of a side-effecting place", span));
                }
                let p = self.place(arg)?;
                let o = if matches!(op, UnaryOp::PreInc | UnaryOp::PostInc) {
                    "++"
                } else {
                    "--"
                };
                let _ = whole;
                if matches!(op, UnaryOp::PostInc | UnaryOp::PostDec) {
                    Ok(format!("func() float64 {{ t := {p}; {p}{o}; return t }}()"))
                } else {
                    Ok(format!("func() float64 {{ {p}{o}; return {p} }}()"))
                }
            }
            _ => Err(unsupported(format!("unary `{:?}` on this type", op), span)),
        }
    }

    fn binary(&mut self, op: BinOp, left: &Expr, right: &Expr, span: Span) -> Result<String> {
        let lt = self.type_of(left)?;
        let rt = self.type_of(right)?;
        let is_nullish = |e: &Expr| {
            matches!(
                e,
                Expr::Lit {
                    value: Literal::Null | Literal::Undefined,
                    ..
                }
            ) || matches!(e, Expr::Ident { name, .. } if name == "undefined")
        };
        // Equality against null/undefined on a nullable value.
        if matches!(
            op,
            BinOp::EqEq | BinOp::EqEqEq | BinOp::NotEq | BinOp::NotEqEq
        ) {
            let neg = matches!(op, BinOp::NotEq | BinOp::NotEqEq);
            let cmp = if neg { "!=" } else { "==" };
            if is_nullish(right) && lt.is_nullable() {
                return Ok(format!("({} {} nil)", self.expr(left)?, cmp));
            }
            if is_nullish(left) && rt.is_nullable() {
                return Ok(format!("({} {} nil)", self.expr(right)?, cmp));
            }
        }
        let a = self.expr(left)?;
        let b = self.expr(right)?;
        let num = lt == GoType::Float && rt == GoType::Float;
        Ok(match op {
            BinOp::Add if num => format!("({} + {})", a, b),
            BinOp::Add if lt == GoType::Str || rt == GoType::Str => {
                let a = self.to_str(a, &lt, span)?;
                let b = self.to_str(b, &rt, span)?;
                format!("({} + {})", a, b)
            }
            BinOp::Sub if num => format!("({} - {})", a, b),
            BinOp::Mul if num => format!("({} * {})", a, b),
            BinOp::Div if num && const_num(right) == Some(0.0) => format!("({} / intyZero)", a),
            BinOp::Div if num => format!("({} / {})", a, b),
            BinOp::Mod if num => format!("intyMod({}, {})", a, b),
            BinOp::Pow if num => format!("intyPow({}, {})", a, b),
            BinOp::Lt | BinOp::Gt | BinOp::LtEq | BinOp::GtEq
                if num || (lt == GoType::Str && rt == GoType::Str) =>
            {
                let o = match op {
                    BinOp::Lt => "<",
                    BinOp::Gt => ">",
                    BinOp::LtEq => "<=",
                    _ => ">=",
                };
                format!("({} {} {})", a, o, b)
            }
            BinOp::EqEq | BinOp::EqEqEq | BinOp::NotEq | BinOp::NotEqEq if lt == rt => {
                let o = if matches!(op, BinOp::EqEq | BinOp::EqEqEq) {
                    "=="
                } else {
                    "!="
                };
                match lt {
                    GoType::Func(..) => {
                        return Err(unsupported("comparing functions", span));
                    }
                    _ => format!("({} {} {})", a, o, b),
                }
            }
            BinOp::And | BinOp::Or if lt == GoType::Bool && rt == GoType::Bool => {
                let o = if op == BinOp::And { "&&" } else { "||" };
                format!("({} {} {})", a, o, b)
            }
            BinOp::BitAnd | BinOp::BitOr | BinOp::BitXor if num => {
                let o = match op {
                    BinOp::BitAnd => "&",
                    BinOp::BitOr => "|",
                    _ => "^",
                };
                format!("float64(intyToInt32({}) {} intyToInt32({}))", a, o, b)
            }
            BinOp::LShift if num => {
                format!("float64(intyToInt32({}) << (intyToUint32({}) & 31))", a, b)
            }
            BinOp::RShift if num => {
                format!("float64(intyToInt32({}) >> (intyToUint32({}) & 31))", a, b)
            }
            BinOp::URShift if num => {
                format!("float64(intyToUint32({}) >> (intyToUint32({}) & 31))", a, b)
            }
            _ => {
                return Err(unsupported(
                    format!(
                        "operator `{:?}` on {} and {}",
                        op,
                        self.tm.render(&lt),
                        self.tm.render(&rt)
                    ),
                    span,
                ))
            }
        })
    }

    /// Emit a call. `stmt` is true in statement position, where a call
    /// returning `undefined` is allowed.
    fn call(&mut self, callee: &Expr, args: &[Expr], span: Span, stmt: bool) -> Result<String> {
        let result = self
            .raw_type(span)
            .and_then(|t| self.tm.map(self.state, &t, span));
        if !stmt && matches!(result, Ok(GoType::Unit)) {
            return Err(unsupported(
                "using the result of a call that returns undefined",
                span,
            ));
        }
        if let Expr::Member {
            object, property, ..
        } = callee
        {
            if let Expr::Ident { name, .. } = &**object {
                if let Some(s) = self.builtin_static(name, property, args, span, stmt)? {
                    return Ok(s);
                }
            }
            match self.type_of(object)? {
                GoType::Array(elem) => {
                    return self.array_method(object, &elem, property, args, span)
                }
                GoType::Str => return self.string_method(object, property, args, span),
                GoType::Struct(_) => {} // a function-valued field: ordinary call below
                _ => {
                    return Err(unsupported(
                        format!("method `.{}` on this type", property),
                        span,
                    ))
                }
            }
        }
        if let Expr::Ident { name, .. } = callee {
            match name.as_str() {
                "String" if args.len() == 1 => {
                    let t = self.type_of(&args[0])?;
                    let v = self.expr(&args[0])?;
                    return self.to_str(v, &t, span);
                }
                "isNaN" if args.len() == 1 => {
                    let v = self.expr(&args[0])?;
                    return Ok(format!("math.IsNaN({})", v));
                }
                _ => {}
            }
        }
        let f = self.expr(callee)?;
        let params = match self.type_of(callee)? {
            GoType::Func(ps, _) => ps,
            _ => return Err(unsupported("call of a non-function", span)),
        };
        if params.len() != args.len() {
            return Err(unsupported("call with omitted optional arguments", span));
        }
        let mut vs = Vec::new();
        for (a, p) in args.iter().zip(&params) {
            vs.push(self.expr_as(a, p)?);
        }
        let f = if matches!(callee, Expr::Ident { .. } | Expr::Member { .. }) {
            f
        } else {
            format!("({})", f)
        };
        Ok(format!("{}({})", f, vs.join(", ")))
    }

    /// `Math.*`, `console.*`, `String.fromCharCode`, `Number.isInteger`.
    fn builtin_static(
        &mut self,
        object: &str,
        property: &str,
        args: &[Expr],
        span: Span,
        stmt: bool,
    ) -> Result<Option<String>> {
        let mut vals = Vec::new();
        let arg = |e: &mut Self, vals: &mut Vec<String>| -> Result<()> {
            for a in args {
                vals.push(e.expr(a)?);
            }
            Ok(())
        };
        Ok(Some(match (object, property) {
            ("console", "log" | "error" | "warn") => {
                if !stmt {
                    return Err(unsupported("using the result of console.log", span));
                }
                let [a] = args else {
                    return Err(unsupported("console.log with several arguments", span));
                };
                let t = self.type_of(a)?;
                if matches!(t, GoType::Array(_)) {
                    // Node's console.log formats arrays specially.
                    return Err(unsupported(
                        "console.log of an array (use .join())",
                        a.span(),
                    ));
                }
                let v = self.expr(a)?;
                // console.log formats numbers with util.inspect, which
                // (unlike String(x)) keeps the sign of -0.
                let s = if t == GoType::Float {
                    format!("intyInspectNum({})", v)
                } else {
                    self.to_str(v, &t, a.span())?
                };
                if property == "log" {
                    format!("intyLog({})", s)
                } else {
                    format!("intyLogErr({})", s)
                }
            }
            ("Math", f) => {
                arg(self, &mut vals)?;
                let go = match f {
                    "abs" => "math.Abs",
                    "floor" => "math.Floor",
                    "ceil" => "math.Ceil",
                    "round" => "intyRound",
                    "trunc" => "math.Trunc",
                    "sign" => "intySign",
                    "sqrt" => "math.Sqrt",
                    "cbrt" => "math.Cbrt",
                    "pow" => "intyPow",
                    // Go 1.21 builtins: NaN-propagating, -0 < +0 — exactly
                    // JS semantics, and compiled inline (math.Min is a call).
                    "min" => "min",
                    "max" => "max",
                    "hypot" => "math.Hypot",
                    "log" => "math.Log",
                    "log2" => "math.Log2",
                    "log10" => "math.Log10",
                    "exp" => "math.Exp",
                    "expm1" => "math.Expm1",
                    "log1p" => "math.Log1p",
                    "sin" => "math.Sin",
                    "cos" => "math.Cos",
                    "tan" => "math.Tan",
                    "asin" => "math.Asin",
                    "acos" => "math.Acos",
                    "atan" => "math.Atan",
                    "atan2" => "math.Atan2",
                    "sinh" => "math.Sinh",
                    "cosh" => "math.Cosh",
                    "tanh" => "math.Tanh",
                    "random" => "rand.Float64",
                    "imul" => "intyImul",
                    "fround" => "intyFround",
                    "clz32" => "intyClz32",
                    _ => return Err(unsupported(format!("Math.{}", f), span)),
                };
                format!("{}({})", go, vals.join(", "))
            }
            ("performance", "now") if args.is_empty() => "intyNow()".into(),
            ("String", "fromCharCode") if args.len() == 1 => {
                arg(self, &mut vals)?;
                format!("intyFromCharCode({})", vals[0])
            }
            ("Number", "isInteger") if args.len() == 1 => {
                arg(self, &mut vals)?;
                format!("intyIsInteger({})", vals[0])
            }
            _ => return Ok(None),
        }))
    }

    fn array_method(
        &mut self,
        object: &Expr,
        elem: &GoType,
        method: &str,
        args: &[Expr],
        span: Span,
    ) -> Result<String> {
        let a = self.expr(object)?;
        let et = self.tm.render(elem);
        let mut vs = Vec::new();
        for x in args {
            vs.push(self.expr_as(x, elem)?);
        }
        let n = args.len();
        Ok(match (method, n) {
            ("push", 1) => format!("intyPush({}, {})", a, vs[0]),
            ("pop", 0) => format!("intyPop({})", a),
            ("indexOf", 1) => format!("intyIndexOf({}, {})", a, vs[0]),
            ("includes", 1) => format!("intyIncludes({}, {})", a, vs[0]),
            ("fill", 1) => format!("intyFill({}, {})", a, vs[0]),
            ("reverse", 0) => format!("intyReverse({})", a),
            ("concat", 1) => {
                let b = self.expr(&args[0])?;
                format!("intyConcat({}, {})", a, b)
            }
            ("slice", _) if n <= 2 => {
                let mut ix = Vec::new();
                for x in args {
                    ix.push(self.expr(x)?);
                }
                let start = ix.first().cloned().unwrap_or_else(|| "0.0".into());
                let end = ix.get(1).cloned().unwrap_or_else(|| "math.Inf(1)".into());
                format!("intySlice({}, {}, {})", a, start, end)
            }
            ("join", _) if n <= 1 => {
                let sep = match args.first() {
                    Some(s) => self.expr(s)?,
                    None => "\",\"".into(),
                };
                let f = self.str_func(elem, span)?;
                format!("intyJoin({}, {}, {})", a, sep, f)
            }
            ("map" | "filter" | "forEach" | "some" | "every" | "findIndex", 1) => {
                let f = self.expr(&args[0])?;
                let helper = match method {
                    "map" => "intyMap",
                    "filter" => "intyFilter",
                    "forEach" => "intyForEach",
                    "some" => "intySome",
                    "every" => "intyEvery",
                    _ => "intyFindIndex",
                };
                format!("{}({}, {})", helper, a, f)
            }
            ("reduce", 2) => {
                let f = self.expr(&args[0])?;
                let acc_t = self.type_of(&args[1])?;
                let acc = self.expr_as(&args[1], &acc_t)?;
                format!("intyReduce({}, {}, {})", a, f, acc)
            }
            _ => {
                let _ = et;
                return Err(unsupported(
                    format!("Array method `.{}`/{}", method, n),
                    span,
                ));
            }
        })
    }

    fn string_method(
        &mut self,
        object: &Expr,
        method: &str,
        args: &[Expr],
        span: Span,
    ) -> Result<String> {
        let s = self.expr(object)?;
        let mut vs = Vec::new();
        for x in args {
            vs.push(self.expr(x)?);
        }
        Ok(match (method, vs.as_slice()) {
            ("charCodeAt", [i]) => format!("float64({}[int({})])", s, i),
            ("indexOf", [x]) => format!("intyStrIndexOf({}, {})", s, x),
            ("includes", [x]) => format!("strings.Contains({}, {})", s, x),
            ("startsWith", [x]) => format!("strings.HasPrefix({}, {})", s, x),
            ("endsWith", [x]) => format!("strings.HasSuffix({}, {})", s, x),
            ("toUpperCase", []) => format!("strings.ToUpper({})", s),
            ("toLowerCase", []) => format!("strings.ToLower({})", s),
            ("trim", []) => format!("strings.TrimSpace({})", s),
            ("repeat", [n]) => format!("strings.Repeat({}, int({}))", s, n),
            ("slice", [a]) => format!("intyStrSlice({}, {}, math.Inf(1))", s, a),
            ("slice", [a, b]) => format!("intyStrSlice({}, {}, {})", s, a, b),
            ("substring", [a]) => format!("intyStrSubstring({}, {}, math.Inf(1))", s, a),
            ("substring", [a, b]) => format!("intyStrSubstring({}, {}, {})", s, a, b),
            _ => return Err(unsupported(format!("String method `.{}`", method), span)),
        })
    }
}
