//! Tests for the Go backend.
//!
//! * Every program under `tests/programs/` and every benchmark under
//!   `examples/go-backend/` must translate.
//! * When a Go toolchain (>= 1.22) is on PATH, each program in
//!   `tests/programs/` is also compiled and run, and its stdout compared
//!   with the `.out` file next to it — output recorded from Node, so the
//!   test pins "the Go binary behaves like the JavaScript under V8".
//!   Without Go the end-to-end part is skipped with a note.

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

fn manifest_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn js_files(dir: &Path) -> Vec<PathBuf> {
    let mut v: Vec<PathBuf> = fs::read_dir(dir)
        .unwrap()
        .map(|e| e.unwrap().path())
        .filter(|p| p.extension().is_some_and(|e| e == "js"))
        .collect();
    v.sort();
    assert!(!v.is_empty(), "no .js files in {}", dir.display());
    v
}

fn translate(path: &Path) -> String {
    let src = fs::read_to_string(path).unwrap();
    match inty_go::compile(&src) {
        Ok(out) => out.code,
        Err(errors) => panic!(
            "{} failed to translate:\n{}",
            path.display(),
            errors
                .iter()
                .map(|e| format!("  {}\n", e))
                .collect::<String>()
        ),
    }
}

fn compile_err(src: &str) -> String {
    match inty_go::compile(src) {
        Ok(out) => panic!("expected an error, got:\n{}", out.code),
        Err(errors) => errors
            .iter()
            .map(|e| e.to_string())
            .collect::<Vec<_>>()
            .join("\n"),
    }
}

#[test]
fn translates_test_programs() {
    for p in js_files(&manifest_dir().join("tests/programs")) {
        let code = translate(&p);
        assert!(code.starts_with("// Code generated by `inty go`"));
        assert!(code.contains("\nfunc main() {\n"));
    }
}

#[test]
fn translates_benchmarks() {
    for p in js_files(&manifest_dir().join("../../examples/go-backend")) {
        translate(&p);
    }
}

#[test]
fn constant_expressions_fold_with_double_rounding() {
    // Go would evaluate `0.1 + 0.2` exactly as a constant expression.
    let code = inty_go::compile("console.log(0.1 + 0.2);").unwrap().code;
    assert!(code.contains("0.30000000000000004"), "{}", code);
}

#[test]
fn objects_become_structs() {
    let code = inty_go::compile(
        "function p(x, y) { return { x: x, y: y }; }\nconst q = p(1, 2);\nconsole.log(q.x + q.y);",
    )
    .unwrap()
    .code;
    assert!(
        code.contains("type Obj1 struct {\n\tx float64\n\ty float64\n}"),
        "{}",
        code
    );
    assert!(
        code.contains("func p(x float64, y float64) *Obj1 {"),
        "{}",
        code
    );
}

#[test]
fn polymorphic_functions_are_monomorphised() {
    // One Go function per concrete instantiation; the first keeps the
    // JS name.
    let code = inty_go::compile(
        "function id(x) { return x; }\nconsole.log(id(1));\nconsole.log(id(\"a\"));",
    )
    .unwrap()
    .code;
    assert!(code.contains("func id(x float64) float64 {"), "{}", code);
    assert!(code.contains("func id__2(x string) string {"), "{}", code);
    assert!(
        code.contains("intyLog(intyInspectNum(id(1.0)))"),
        "{}",
        code
    );
    assert!(code.contains("intyLog(id__2(\"a\"))"), "{}", code);
}

#[test]
fn same_go_types_share_a_specialisation() {
    // Two uses that differ only in literal types reuse one copy.
    let code =
        inty_go::compile("function id(x) { return x; }\nconsole.log(id(1));\nconsole.log(id(2));")
            .unwrap()
            .code;
    assert!(code.contains("func id(x float64) float64 {"), "{}", code);
    assert!(!code.contains("id__2"), "{}", code);
}

#[test]
fn unreachable_functions_are_not_emitted() {
    let code = inty_go::compile("function unused(x) { return x; }\nconsole.log(1);")
        .unwrap()
        .code;
    assert!(!code.contains("unused"), "{}", code);
}

#[test]
fn unsupported_constructs_are_reported_not_mistranslated() {
    let err = compile_err("try { console.log(1); } catch (e) { console.log(2); }");
    assert!(
        err.contains("try/catch") && err.contains("not supported by the Go backend"),
        "{}",
        err
    );
    let err = compile_err("const o = { n: 1, get() { return this.n; } };\nconsole.log(o.get());");
    assert!(err.contains("`this`"), "{}", err);
}

#[test]
fn type_errors_are_reported() {
    let err = compile_err("const x = 1;\nconsole.log(x + \"a\");");
    assert!(!err.is_empty());
}

/// `go version` output parsed to (major, minor), if Go is installed.
fn go_version() -> Option<(u32, u32)> {
    let out = Command::new("go").arg("version").output().ok()?;
    let text = String::from_utf8(out.stdout).ok()?;
    let v = text
        .split_whitespace()
        .find_map(|w| w.strip_prefix("go1."))?;
    let minor: u32 = v
        .split(|c: char| !c.is_ascii_digit())
        .next()?
        .parse()
        .ok()?;
    Some((1, minor))
}

#[test]
fn go_binaries_match_node_output() {
    match go_version() {
        Some((1, minor)) if minor >= 22 => {}
        other => {
            eprintln!(
                "skipping end-to-end Go test: need go >= 1.22, found {:?}",
                other
            );
            return;
        }
    }
    let work = std::env::temp_dir().join(format!("inty-go-e2e-{}", std::process::id()));
    let mut failures = Vec::new();
    for p in js_files(&manifest_dir().join("tests/programs")) {
        let name = p.file_stem().unwrap().to_string_lossy().to_string();
        let dir = work.join(&name);
        fs::create_dir_all(&dir).unwrap();
        fs::write(dir.join("main.go"), translate(&p)).unwrap();
        fs::write(dir.join("go.mod"), "module prog\n\ngo 1.22\n").unwrap();
        let build = Command::new("go")
            .args(["build", "-o", "prog", "."])
            .current_dir(&dir)
            .output()
            .unwrap();
        if !build.status.success() {
            failures.push(format!(
                "{}: go build failed:\n{}",
                name,
                String::from_utf8_lossy(&build.stderr)
            ));
            continue;
        }
        let run = Command::new(dir.join("prog")).output().unwrap();
        let expected = fs::read_to_string(p.with_extension("out")).unwrap();
        let actual = String::from_utf8_lossy(&run.stdout);
        if !run.status.success() || actual != expected {
            failures.push(format!(
                "{}: output differs from node\n--- expected\n{}--- actual\n{}{}",
                name,
                expected,
                actual,
                String::from_utf8_lossy(&run.stderr)
            ));
        }
    }
    let _ = fs::remove_dir_all(&work);
    assert!(failures.is_empty(), "{}", failures.join("\n"));
}

/// Build translated Go `code` in `dir`; the binary's path, or the build
/// errors.
fn go_build(dir: &Path, code: &str) -> Result<PathBuf, String> {
    fs::create_dir_all(dir).unwrap();
    fs::write(dir.join("main.go"), code).unwrap();
    fs::write(dir.join("go.mod"), "module prog\n\ngo 1.22\n").unwrap();
    let build = Command::new("go")
        .args(["build", "-o", "prog", "."])
        .current_dir(dir)
        .output()
        .unwrap();
    if build.status.success() {
        Ok(dir.join("prog"))
    } else {
        Err(String::from_utf8_lossy(&build.stderr).into_owned())
    }
}

/// Run `bin` with `args` and `stdin`: (exit code, stdout, stderr).
fn run_with(bin: &Path, args: &[&str], stdin: &[u8]) -> (i32, String, String) {
    use std::io::Write;
    let mut child = Command::new(bin)
        .args(args)
        .stdin(std::process::Stdio::piped())
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .spawn()
        .unwrap();
    child.stdin.take().unwrap().write_all(stdin).unwrap();
    let out = child.wait_with_output().unwrap();
    (
        out.status.code().unwrap_or(-1),
        String::from_utf8_lossy(&out.stdout).into_owned(),
        String::from_utf8_lossy(&out.stderr).into_owned(),
    )
}

fn go_available() -> bool {
    match go_version() {
        Some((1, minor)) if minor >= 22 => true,
        other => {
            eprintln!("skipping end-to-end Go test: need go >= 1.22, found {:?}", other);
            false
        }
    }
}

/// Node built-ins (`node:fs`, `node:process`): arguments, reading and
/// writing files, stdout/stderr and the exit status all behave as under
/// Node (the expected output in `tests/io/` was recorded from Node).
#[test]
fn node_io_matches_node() {
    if !go_available() {
        return;
    }
    let io = manifest_dir().join("tests/io");
    let work = std::env::temp_dir().join(format!("inty-go-io-{}", std::process::id()));
    let bin = go_build(&work.join("io"), &translate(&io.join("io.js"))).unwrap();
    let outdir = work.join("out");
    fs::create_dir_all(&outdir).unwrap();
    let input = io.join("input.txt");
    let (code, stdout, stderr) = run_with(
        &bin,
        &[input.to_str().unwrap(), outdir.to_str().unwrap()],
        b"",
    );
    assert_eq!(stdout, fs::read_to_string(io.join("io.out")).unwrap());
    assert_eq!(stderr, fs::read_to_string(io.join("io.err")).unwrap());
    assert_eq!(code, 3, "process.exit(3)");
    assert_eq!(fs::read_to_string(outdir.join("out.txt")).unwrap(), "first\nsecond\n");
    // Wrong usage: message on stderr, exit status 2.
    let (code, stdout, stderr) = run_with(&bin, &[], b"");
    assert_eq!((code, stdout.as_str()), (2, ""));
    assert!(stderr.starts_with("usage: io"), "{}", stderr);
    let _ = fs::remove_dir_all(&work);
}

/// The md2html tool (`examples/go-backend/tools/md2html.js`) produces the
/// same HTML as under Node, from a file, from stdin, and to a file.
#[test]
fn md2html_matches_node() {
    if !go_available() {
        return;
    }
    let io = manifest_dir().join("tests/io");
    let tool = manifest_dir().join("../../examples/go-backend/tools/md2html.js");
    let work = std::env::temp_dir().join(format!("inty-go-md2html-{}", std::process::id()));
    let bin = go_build(&work.join("md2html"), &translate(&tool)).unwrap();
    let sample = io.join("sample.md");
    let md = fs::read(&sample).unwrap();
    let html = fs::read_to_string(io.join("sample.html")).unwrap();
    assert_eq!(run_with(&bin, &[sample.to_str().unwrap()], b"").1, html);
    assert_eq!(run_with(&bin, &["-"], &md).1, html);
    let out = work.join("standalone.html");
    let (code, stdout, _) = run_with(
        &bin,
        &["--standalone", "-o", out.to_str().unwrap(), sample.to_str().unwrap()],
        b"",
    );
    assert_eq!((code, stdout.as_str()), (0, ""));
    assert_eq!(
        fs::read_to_string(&out).unwrap(),
        fs::read_to_string(io.join("sample.standalone.html")).unwrap()
    );
    let (code, _, stderr) = run_with(&bin, &["--bogus"], b"");
    assert_eq!(code, 2);
    assert!(stderr.contains("unknown option --bogus"), "{}", stderr);
    let _ = fs::remove_dir_all(&work);
}

/// Small inputs that reach the rarer paths of fast-diff's cleanup passes:
/// (1) eliminating the first equality (upstream's equality stack goes
/// negative) and a forward overlap, (2) a reverse overlap, (3) an edit
/// slid over the following equality. Semantic cleanup depends on what
/// precedes an edit, so each is diffed on its own. Their expected output,
/// with and without `--cleanup`, is in `tests/io/fastdiff.edge.out`.
const FASTDIFF_EDGE_CASES: &[(&str, &str)] = &[
    (
        "the badefdefba baa badefcat camecat defxxxcamea\n\nabbacat ",
        "bcamecame\n\ncat   the \n\n",
    ),
    ("abaxxx\n\n", " defbaabxxx"),
    ("abc xxxcame ", "the abb.\nab"),
];

/// The fastdiff tool (`examples/go-backend/tools/fastdiff.js`, a port of
/// npm fast-diff) prints the same diff as under Node, with and without
/// `--cleanup`. The expected output in `tests/io/fastdiff*.out` was
/// recorded from Node and agrees with the upstream package.
#[test]
fn fastdiff_matches_node() {
    if !go_available() {
        return;
    }
    let io = manifest_dir().join("tests/io");
    let tool = manifest_dir().join("../../examples/go-backend/tools/fastdiff.js");
    let work = std::env::temp_dir().join(format!("inty-go-fastdiff-{}", std::process::id()));
    let bin = go_build(&work.join("fastdiff"), &translate(&tool)).unwrap();
    let old = io.join("fastdiff.old.txt");
    let new = io.join("fastdiff.new.txt");
    let (old, new) = (old.to_str().unwrap(), new.to_str().unwrap());
    let (code, stdout, _) = run_with(&bin, &[old, new], b"");
    assert_eq!(code, 0);
    assert_eq!(stdout, fs::read_to_string(io.join("fastdiff.out")).unwrap());
    let (code, stdout, _) = run_with(&bin, &[old, "--cleanup", new], b"");
    assert_eq!(code, 0);
    assert_eq!(
        stdout,
        fs::read_to_string(io.join("fastdiff.cleanup.out")).unwrap()
    );

    let mut edge = String::new();
    for (i, (a, b)) in FASTDIFF_EDGE_CASES.iter().enumerate() {
        let (fa, fb) = (work.join("a.txt"), work.join("b.txt"));
        fs::write(&fa, a).unwrap();
        fs::write(&fb, b).unwrap();
        for cleanup in [false, true] {
            let mut args = vec![fa.to_str().unwrap(), fb.to_str().unwrap()];
            if cleanup {
                args.push("--cleanup");
            }
            let (code, stdout, stderr) = run_with(&bin, &args, b"");
            assert_eq!(code, 0, "edge case {}: {}", i + 1, stderr);
            edge.push_str(&format!(
                "# edge case {}{}\n{}",
                i + 1,
                if cleanup { " --cleanup" } else { "" },
                stdout
            ));
        }
    }
    assert_eq!(
        edge,
        fs::read_to_string(io.join("fastdiff.edge.out")).unwrap()
    );

    // Wrong usage: message on stderr, exit status 2.
    let (code, stdout, stderr) = run_with(&bin, &[old], b"");
    assert_eq!((code, stdout.as_str()), (2, ""));
    assert!(stderr.contains("usage: fastdiff"), "{}", stderr);
    let (code, _, stderr) = run_with(&bin, &[old, new, "--bogus"], b"");
    assert_eq!(code, 2);
    assert!(stderr.contains("unknown option --bogus"), "{}", stderr);
    let _ = fs::remove_dir_all(&work);
}

/// `splice` takes at most `SPLICE_MAX_ITEMS` inserted items (there are no
/// variadic function types): a call with more is a type error, never a
/// mistranslation.
#[test]
fn splice_with_too_many_items_is_rejected() {
    let err =
        compile_err("const a = [1, 2];\na.splice(0, 0, 1, 2, 3, 4, 5);\nconsole.log(a.length);");
    assert!(!err.is_empty());
    let four = "const a = [1, 2];\na.splice(0, 0, 1, 2, 3, 4);\nconsole.log(a.length);";
    assert!(inty_go::compile(four).is_ok());
}
