//! Tests for the Go backend.
//!
//! * Every program under `tests/programs/` and every benchmark under
//!   `examples/go-backend/` must translate.
//! * When a Go toolchain (>= 1.22) is on PATH, each program in
//!   `tests/programs/` is also compiled and run, and its stdout compared
//!   with the `.out` file next to it — output recorded from Node, so the
//!   test pins "the Go binary behaves like the JavaScript under V8".
//!   Without Go the end-to-end part is skipped with a note.

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

fn manifest_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn js_files(dir: &Path) -> Vec<PathBuf> {
    let mut v: Vec<PathBuf> = fs::read_dir(dir)
        .unwrap()
        .map(|e| e.unwrap().path())
        .filter(|p| p.extension().is_some_and(|e| e == "js"))
        .collect();
    v.sort();
    assert!(!v.is_empty(), "no .js files in {}", dir.display());
    v
}

fn translate(path: &Path) -> String {
    let src = fs::read_to_string(path).unwrap();
    match inty_go::compile(&src) {
        Ok(out) => out.code,
        Err(errors) => panic!(
            "{} failed to translate:\n{}",
            path.display(),
            errors
                .iter()
                .map(|e| format!("  {}\n", e))
                .collect::<String>()
        ),
    }
}

fn compile_err(src: &str) -> String {
    match inty_go::compile(src) {
        Ok(out) => panic!("expected an error, got:\n{}", out.code),
        Err(errors) => errors
            .iter()
            .map(|e| e.to_string())
            .collect::<Vec<_>>()
            .join("\n"),
    }
}

#[test]
fn translates_test_programs() {
    for p in js_files(&manifest_dir().join("tests/programs")) {
        let code = translate(&p);
        assert!(code.starts_with("// Code generated by `inty go`"));
        assert!(code.contains("\nfunc main() {\n"));
    }
}

#[test]
fn translates_benchmarks() {
    for p in js_files(&manifest_dir().join("../../examples/go-backend")) {
        translate(&p);
    }
}

#[test]
fn constant_expressions_fold_with_double_rounding() {
    // Go would evaluate `0.1 + 0.2` exactly as a constant expression.
    let code = inty_go::compile("console.log(0.1 + 0.2);").unwrap().code;
    assert!(code.contains("0.30000000000000004"), "{}", code);
}

#[test]
fn objects_become_structs() {
    let code = inty_go::compile(
        "function p(x, y) { return { x: x, y: y }; }\nconst q = p(1, 2);\nconsole.log(q.x + q.y);",
    )
    .unwrap()
    .code;
    assert!(
        code.contains("type Obj1 struct {\n\tx float64\n\ty float64\n}"),
        "{}",
        code
    );
    assert!(
        code.contains("func p(x float64, y float64) *Obj1 {"),
        "{}",
        code
    );
}

#[test]
fn polymorphic_functions_are_monomorphised() {
    // One Go function per concrete instantiation; the first keeps the
    // JS name.
    let code = inty_go::compile(
        "function id(x) { return x; }\nconsole.log(id(1));\nconsole.log(id(\"a\"));",
    )
    .unwrap()
    .code;
    assert!(code.contains("func id(x float64) float64 {"), "{}", code);
    assert!(code.contains("func id__2(x string) string {"), "{}", code);
    assert!(
        code.contains("intyLog(intyInspectNum(id(1.0)))"),
        "{}",
        code
    );
    assert!(code.contains("intyLog(id__2(\"a\"))"), "{}", code);
}

#[test]
fn same_go_types_share_a_specialisation() {
    // Two uses that differ only in literal types reuse one copy.
    let code =
        inty_go::compile("function id(x) { return x; }\nconsole.log(id(1));\nconsole.log(id(2));")
            .unwrap()
            .code;
    assert!(code.contains("func id(x float64) float64 {"), "{}", code);
    assert!(!code.contains("id__2"), "{}", code);
}

#[test]
fn unreachable_functions_are_not_emitted() {
    let code = inty_go::compile("function unused(x) { return x; }\nconsole.log(1);")
        .unwrap()
        .code;
    assert!(!code.contains("unused"), "{}", code);
}

#[test]
fn unsupported_constructs_are_reported_not_mistranslated() {
    let err = compile_err("try { console.log(1); } catch (e) { console.log(2); }");
    assert!(
        err.contains("try/catch") && err.contains("not supported by the Go backend"),
        "{}",
        err
    );
    let err = compile_err("const o = { n: 1, get() { return this.n; } };\nconsole.log(o.get());");
    assert!(err.contains("`this`"), "{}", err);
}

#[test]
fn type_errors_are_reported() {
    let err = compile_err("const x = 1;\nconsole.log(x + \"a\");");
    assert!(!err.is_empty());
}

/// `go version` output parsed to (major, minor), if Go is installed.
fn go_version() -> Option<(u32, u32)> {
    let out = Command::new("go").arg("version").output().ok()?;
    let text = String::from_utf8(out.stdout).ok()?;
    let v = text
        .split_whitespace()
        .find_map(|w| w.strip_prefix("go1."))?;
    let minor: u32 = v
        .split(|c: char| !c.is_ascii_digit())
        .next()?
        .parse()
        .ok()?;
    Some((1, minor))
}

#[test]
fn go_binaries_match_node_output() {
    match go_version() {
        Some((1, minor)) if minor >= 22 => {}
        other => {
            eprintln!(
                "skipping end-to-end Go test: need go >= 1.22, found {:?}",
                other
            );
            return;
        }
    }
    let work = std::env::temp_dir().join(format!("inty-go-e2e-{}", std::process::id()));
    let mut failures = Vec::new();
    for p in js_files(&manifest_dir().join("tests/programs")) {
        let name = p.file_stem().unwrap().to_string_lossy().to_string();
        let dir = work.join(&name);
        fs::create_dir_all(&dir).unwrap();
        fs::write(dir.join("main.go"), translate(&p)).unwrap();
        fs::write(dir.join("go.mod"), "module prog\n\ngo 1.22\n").unwrap();
        let build = Command::new("go")
            .args(["build", "-o", "prog", "."])
            .current_dir(&dir)
            .output()
            .unwrap();
        if !build.status.success() {
            failures.push(format!(
                "{}: go build failed:\n{}",
                name,
                String::from_utf8_lossy(&build.stderr)
            ));
            continue;
        }
        let run = Command::new(dir.join("prog")).output().unwrap();
        let expected = fs::read_to_string(p.with_extension("out")).unwrap();
        let actual = String::from_utf8_lossy(&run.stdout);
        if !run.status.success() || actual != expected {
            failures.push(format!(
                "{}: output differs from node\n--- expected\n{}--- actual\n{}{}",
                name,
                expected,
                actual,
                String::from_utf8_lossy(&run.stderr)
            ));
        }
    }
    let _ = fs::remove_dir_all(&work);
    assert!(failures.is_empty(), "{}", failures.join("\n"));
}
