#!/usr/bin/env python3
"""Generate web/examples.js from examples/playground/.

The on-disk layout under `examples/playground/` is the source of
truth — both the web playground and the Rust integration tests
consume it. This script projects it into the ES module shape that
`web/app.js` imports.

Sections may carry a `language` field (`javascript`, `python`, `lua`).
Items default to a `.<ext>` file matching their `id`; an explicit
`file` field overrides this when the on-disk file name diverges from
the example id (used by Python examples where ids are namespaced).
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC_DIR = ROOT.joinpath("examples", "playground")
OUT_FILE = ROOT.joinpath("web", "examples.js")

LANG_EXT = {
    "javascript": "js",
    "python": "py",
    "lua": "lua",
}


def js_string(s: str) -> str:
    """Encode a Python str as a JS template literal body.

    Template literals let us preserve newlines verbatim; only the
    backtick, backslash, and ${ sequence need escaping.
    """
    return (
        s.replace("\\", "\\\\")
         .replace("`", "\\`")
         .replace("${", "\\${")
    )


def main() -> int:
    manifest_path = SRC_DIR.joinpath("manifest.json")
    manifest = json.loads(manifest_path.read_text())

    # Back-compat: old manifest had a flat `default` key and no per-
    # section `language`. New manifest has `defaults: { language: id }`.
    defaults = manifest.get("defaults")
    if defaults is None:
        defaults = {"javascript": manifest["default"]}

    out = []
    out.append("// AUTO-GENERATED by scripts/gen-examples.py — do not edit by hand.")
    out.append("// Source: examples/playground/")
    out.append("")
    out.append("export const EXAMPLES = [")

    for section in manifest["sections"]:
        language = section.get("language", "javascript")
        ext = LANG_EXT.get(language)
        if ext is None:
            print(f"error: unknown language {language!r} in section {section['id']}", file=sys.stderr)
            return 1

        out.append("    {")
        out.append(f"        id: {json.dumps(section['id'])},")
        out.append(f"        language: {json.dumps(language)},")
        out.append(f"        label: {json.dumps(section['label'])},")
        out.append("        items: [")
        for item in section["items"]:
            file_name = item.get("file") or f"{item['id']}.{ext}"
            file_path = SRC_DIR.joinpath(section["id"], file_name)
            if not file_path.is_file():
                print(f"error: missing example file {file_path}", file=sys.stderr)
                return 1
            code = file_path.read_text()
            out.append("            {")
            out.append(f"                id: {json.dumps(item['id'])},")
            out.append(f"                language: {json.dumps(language)},")
            out.append(f"                label: {json.dumps(item['label'])},")
            out.append(f"                blurb: {json.dumps(item['blurb'])},")
            out.append(f"                expect: {json.dumps(item['expect'])},")
            out.append(f"                code: `{js_string(code)}`,")
            out.append("            },")
        out.append("        ],")
        out.append("    },")

    out.append("];")
    out.append("")
    out.append("export function findExample(id) {")
    out.append("    for (const section of EXAMPLES) {")
    out.append("        for (const item of section.items) {")
    out.append("            if (item.id === id) return { section, item };")
    out.append("        }")
    out.append("    }")
    out.append("    return null;")
    out.append("}")
    out.append("")
    out.append(f"export const DEFAULT_EXAMPLE_IDS = {json.dumps(defaults)};")
    # Back-compat alias so older bundles keep working until the next deploy.
    js_default = defaults.get("javascript") or next(iter(defaults.values()))
    out.append(f"export const DEFAULT_EXAMPLE_ID = {json.dumps(js_default)};")
    out.append("")

    OUT_FILE.write_text("\n".join(out))
    print(f"wrote {OUT_FILE.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
