# Built-in `argparse` module stub for inty. Parsed namespaces are dynamic,
# so `parse_args()` returns an opaque value.
class ArgumentParser:
    def __init__(self) -> None: ...
    def add_argument(self, name: str) -> None: ...
    def parse_args(self) -> object: ...
    def add_subparsers(self) -> object: ...
    def print_help(self) -> None: ...
