# Built-in `os` module stub for inty. `os.path` is a submodule exposed
# opaquely here (member access reads through it), so `os.path.join(...)`
# resolves without a dedicated `os/path` stub.
path: object
environ: object
sep: str
linesep: str
def getcwd() -> str: ...
def chdir(path: object) -> None: ...
def getenv(key: str) -> object: ...
def listdir(path: str = ...) -> list[str]: ...
def makedirs(path: str) -> None: ...
def remove(path: str) -> None: ...
def unlink(path: object) -> None: ...
