# Built-in `pathlib` module stub for inty. The `/` join operator is
# numeric-only (`Div` typeclass), so `Path / str` does not type-check
# today; users go through `.joinpath(...)` instead.
class Path:
    def __init__(self, p: str = ...) -> None: ...
    def exists(self) -> bool: ...
    def is_file(self) -> bool: ...
    def is_dir(self) -> bool: ...
    def read_text(self) -> str: ...
    def write_text(self, data: str) -> None: ...
    def mkdir(self) -> None: ...
    def relative_to(self, other: str) -> Path: ...
    def joinpath(self, other: str) -> Path: ...
    def resolve(self) -> Path: ...
    name: str
    stem: str
    suffix: str
    parent: Path
