# Built-in `pathlib` module stub for inty. The `/` join operator is
# typed via a Python `Div` typeclass instance for `Path` registered by
# `frontends::python::instances` — not via a `__truediv__` field on the
# class. The stub therefore omits the dunder.
class Path:
    def __init__(self, p: str = ...) -> None: ...
    def exists(self) -> bool: ...
    def is_file(self) -> bool: ...
    def is_dir(self) -> bool: ...
    def read_text(self) -> str: ...
    def write_text(self, data: str) -> None: ...
    def mkdir(self) -> None: ...
    def relative_to(self, other: str) -> Path: ...
    def joinpath(self, other: str) -> Path: ...
    def resolve(self) -> Path: ...
    name: str
    stem: str
    suffix: str
    parent: Path
