# Built-in `pathlib` module stub for inty. The `/` join operator
# (`Path.__truediv__`) is a user operator protocol inty doesn't model
# (see issue #39); the rest of the surface is here.
class Path:
    def __init__(self, p: str = ...) -> None: ...
    def exists(self) -> bool: ...
    def is_file(self) -> bool: ...
    def is_dir(self) -> bool: ...
    def read_text(self) -> str: ...
    def write_text(self, data: str) -> None: ...
    def mkdir(self) -> None: ...
    def relative_to(self, other: object) -> Path: ...
    def joinpath(self, other: str) -> Path: ...
    def resolve(self) -> Path: ...
    name: str
    stem: str
    suffix: str
    parent: Path
