# Built-in `re` module stub for inty. A compiled pattern is a nominal
# class; match objects are opaque (their group API is dynamic).
DOTALL: int
IGNORECASE: int
MULTILINE: int
VERBOSE: int

class Pattern:
    def search(self, s: str) -> object: ...
    def match(self, s: str) -> object: ...
    def fullmatch(self, s: str) -> object: ...
    def findall(self, s: str) -> list[str]: ...
    def split(self, s: str) -> list[str]: ...
    def sub(self, repl: str, s: str, count: int = ...) -> str: ...
    def subn(self, repl: str, s: str, count: int = ...) -> object: ...

def compile(pattern: str) -> Pattern: ...
def search(pattern: str, s: str) -> object: ...
def match(pattern: str, s: str) -> object: ...
def findall(pattern: str, s: str) -> list[str]: ...
def sub(pattern: str, repl: str, s: str) -> str: ...
def escape(s: str) -> str: ...
