# Built-in `subprocess` module stub for inty.
class CompletedProcess:
    def __init__(self) -> None: ...
    returncode: int
    stdout: str
    stderr: str

class CalledProcessError:
    def __init__(self) -> None: ...
    returncode: int
    cmd: list[str]

PIPE: int
DEVNULL: int
def run(cmd: list[str]) -> CompletedProcess: ...
def call(cmd: list[str]) -> int: ...
def check_call(cmd: list[str]) -> int: ...
def check_output(cmd: list[str]) -> str: ...
